### ISSUE TITLE
Unmounting problem.

### ISSUE THREAD

**Issue by Achaean** [mhogomchungu/sirikali#101]
Hi! :-)

Seems like if there's an open document (eg. a text file, still opened on a text editor) and you click "Unmount All" (or "Unmount All and Quit"), unmounting fails silently.

Maybe it should be useful, bringing an error message about it (so you could deal with it)).
Latest version (1.3.8) from repository for Debian, on Devuan ASCII (stable) x64 KDE (Debian stable based).

Bye! :-)

**Comment by mhogomchungu** [comment]
This is by design.

Lets say you have 5 opened volumes that could not be locked for whatever reason, your proposal would lead to 5 "can not unmount prompts" and i thought this will be a bad UX.

In the above scenario, would you prefer to have 5 prompts, each prompt for its respective failed attempt or a single prompt or a single prompt that says something like "atleast one volume failed to unmount"?

**Comment by Achaean** [comment]
Oh....I see!
Actually I never thought this scenario. (Personally I only have 1).
In this case (I think) a single message it would be more practical.
Something like "Unable to unmount one or more volumes".

In any case, if this is a feature (not a bug), I didn't mean to alter the design or the expected behavior of the program.
Bye! :-)

**Comment by mhogomchungu** [comment]
I just implemented your suggestion.

https://github.com/mhogomchungu/sirikali/commit/806094873b96f431605aa6bba92e5f2f3d80d205

**Comment by Achaean** [comment]
**THANKS** Francis!!!  ;-)
