### ISSUE TITLE
IMHO: Wallet management not very intuitive

### ISSUE THREAD

**Issue by r3r57** [mhogomchungu/sirikali#102]
In the current version the wallet management seems kind of unintuitive.
1. First I expected there would be a prompt when creating a new volume (gocryptfs) and use Internal/Gnome wallet which would allow me to set a password and save it in the wallet. But this fails with 'The Volume Does Not Appear To Have An Entry In The Wallet'.
2. So I created a new entry in my wallet with the specific volume path and set a password. Then I tried to create the volume again and choose the wallet but again it said 'The Volume Does Not Appear To Have An Entry In The Wallet'.
3. The only working solution was to create a new volume with 'Key' and set a password, create a new entry in the wallet, and then choose the wallet on the mount prompt next time.

Since you normally have to do this procedure only on time for each volume it's not that much of a hassle but I think it doesn't hurt to improve this.

So my question is: Do you think it's feasible to implement (1.)? Whenever I create a new volume and choose a wallet, there should be a prompt (`src/walletconfiginput.ui`) with prefilled 'Volume ID'?

I'd be willing to submit a PR but I'm not a CPP developer nor used Qt. But I'll give it a try ;)

**Comment by mhogomchungu** [comment]
The git version now does what you want.

When creating a new volume, select "Gnome Wallet" and you will see a prompt as seen below.

Enter your key and SiriKali will first add the key in Gnome's Wallet(libsecret) and then create a volume with the key.

Will appreciate if could confirm that it works.

![Screenshot_20190620_182215](https://user-images.githubusercontent.com/3496115/59860975-9966d780-9388-11e9-9fb2-4f47d0f066c6.png)

**Comment by r3r57** [comment]
Hello @mhogomchungu,
thank you very much for the fast response and implementation. I also implemented a solution trying to reuse as much of your code as possible. I'll create a PR but you can close it without commenting.

![peek-fix](https://user-images.githubusercontent.com/24757415/59863822-cbc30580-9385-11e9-99a1-b7557198542f.gif)

I'd would like to see your solution with similar features as when you create the entry through the settings: confirm password, add comment to entry.

At the end you can see, that the internal wallet doesn't work, after entering the wallet's password (`./sirikali” terminated by signal SIGSEGV (Address boundary error)`). This is also in the `master`:

![peek-issue](https://user-images.githubusercontent.com/24757415/59864973-37a66d80-9388-11e9-9813-96327c7b790c.gif)

I'll take a look at it, because it might be a problem with my installation. Otherwise I'll create a new issue. Can you tell me if it the internal wallet works for you?

**Comment by mhogomchungu** [comment]
The internal wallet works for me and its the only one i use. You are not the first person to report a crash using it so i guess i need to revisit it.

SiriKali hangs when it produces multiple windows on MACOS and thats why i try very hard to reuse the password dialog window.

I dont have a MAC and its not easy testing on it and i only do what i already know it works there. you will have to show that your way works on MACOS before i will accept it.

If you like your way better than mine then you should add it on top of my solution and add a config option to switch between the two and with my solution being the default.
```
 QString message = QString("The Volume Does Not Appear To Have An Entry In The Wallet.\nDo You Want To Create A New One?");
```

The above is wrong because its not translatable, it should like below
```
```
 QString message = tr("The Volume Does Not Appear To Have An Entry In The Wallet.\nDo You Want To Create A New One?");
```
```
