### ISSUE TITLE
Provide macOS installation instructions on homepage

### ISSUE THREAD

**Issue by ylogx** [mhogomchungu/sirikali#114]
The [homepage](https://mhogomchungu.github.io/sirikali/#download-links-for-microsoft-windows-operating-system) describes steps for windows and linux installation. It'll be benificial to users if it describes steps to install this on mac.

**Comment by mhogomchungu** [comment]
I don't have a mac, i have never used a mac and all the mac support you see comes from users like yourself.

Tell me what to add and i will blindly add them to the front page because i cant test myself.

**Comment by mhogomchungu** [comment]
Closing this one for lack of activity.

**Comment by mhogomchungu** [comment]
Its currently not easy to install on a mac because i dont have the hardware to test and do  it myself but i have added manual steps to do it and they are documented here[1]. This is the best i can do for now and the steps are too many to add them to the front page.

[1] https://github.com/mhogomchungu/sirikali/blob/master/OSX_BUILD_INSTRUCTIONS
