### ISSUE TITLE
Add support for fscrypt

### ISSUE THREAD

**Issue by varrel1337** [mhogomchungu/sirikali#122]
One of the new modern backends for filesystem encryption is fscrypt. 
It would be awesome to see support for this backend in sirikali

**Comment by mhogomchungu** [comment]
Post a link to the project.

**Comment by varrel1337** [comment]
Userspace tool:
https://github.com/google/fscrypt
Documentation
https://docs.google.com/document/d/1GBbuCMe-wLuXosVI87cv8CuRkqwncpnNdXAJDECP-6w/edit

**Comment by mhogomchungu** [comment]
What is your usecase for this tool and why do you think its better than the likes of cryfs, securefs, gocryptfs, eCryptfs?

This tools encrypts contents of folders so its in the same league as the mentioned project but it behaves very differently.

Below is the odd things i have so far seen from this tool.

Lets say you have a mount point path of "/mnt/foo".

1. The mount point path can not be encrypted, you can only encrypt folders inside the mount point.
2, Lets create two encrypted folders named "abc" and "def".
3. The two encrypted folders can be unlocked independently of each other but can not be locked
   independently of each each since the locking part is done with the mount point path and it
   locks all unlocked volumes in the mount path.
4. The locking needs to be done from root's account to make sure nothing leaks after a volume is locked and
   the mount point needs to be unmounted for good measure.
5. This tool seems to be designed with a view of one mount point for one encrypted subfolder but it allows
   many encrypted folders to be created in the same mount point and this seems strange.
   

From a distance, this tool looks like the rest of the supported backends since it deals with encryption of folder
contents but it behaves very differently and the biggest differences i have seen so far are:
1. An unlocked volume does not add its entry in /proc/self/mountinfo(This will probably be a deal breaker).
2. Ciphertext path and cleartext path are the same.
3. When locking a volume, a completely different path is used(How to figure this one out?).
4. Locking one volumes means locking all volumes in the same mount point path(very, very, very strange).

It will be nice to support this but it wont be easy.

**Comment by ebiggers** [comment]
google/fscrypt#148 will add an `fscrypt lock` command to mirror `fscrypt unlock`, as well as add support for v2 encryption policies which don't require root to lock.

Also, fscrypt refers to the Linux native filesystem encryption, e.g. ext4 encryption, so there's no such thing as an "fscrypt volume" or "fscrypt mountpoint".  The encrypted directories are simply directories on the underlying ext4 filesystem, not separate filesystems or mountpoints.

**Comment by mhogomchungu** [comment]
The git version can now unlock and lock encrypted directories and the main UI will be as seen in the second image below.

It will be up the user to figure out what directory corresponds to those entries and the comment part could be a useful hint,

fscrypt currently requires root's privileges so expect a polkit prompt the first time you use the backend after the program is started.

![Screenshot_20191010_223326](https://user-images.githubusercontent.com/3496115/66600885-3e632580-ebaf-11e9-9ccf-9c91fd20dcc3.png)
![Screenshot_20191010_223354](https://user-images.githubusercontent.com/3496115/66600886-3e632580-ebaf-11e9-9803-f1fec700c276.png)

**Comment by mhogomchungu** [comment]
The git version now has the full support for this backend.

By default, SiriKali:
1. Creates an encrypted directory from the normal user account.
2. Unlocks an encrypted directory from the normal user account.
3. Lock an unlocked directories from the normal user account because it passed
    ```--drop-caches=false``` option to fscrypt. This option provides the best
   user experience but i understand it has some security issues. There is a SiriKali config option
   named ```RequirePolkitOnFsCryptUnmount``` that can be used to ask fscrypt to
   drop caches. Fscrypt requires to be run from root's account with this option and
   SiriKali will generate a polkit prompt when it is set.

SiriKali configuration file is located at ```~/.config/SiriKali/SiriKali.conf```

Testers will be appreciated.

**Comment by varrel1337** [comment]
Wow, thank you this is awesome. Did not expect to see support this soon.

**Comment by mhogomchungu** [comment]
New version is out and it has this feature.

https://github.com/mhogomchungu/sirikali/releases/tag/1.4.1
