### ISSUE TITLE
command line options

### ISSUE THREAD

**Issue by lawmanuk** [mhogomchungu/sirikali#126]
Are there any command line options to run sirikali

eg.   run and mount x favourite with x password at startup etc.

trying to automate mounting at startup without password entry for cryfs container.

thanks

**Comment by mhogomchungu** [comment]
You can do what you want with a GUI by doing the following.
0. Set your DE to start SiriKali at login time.
1. Set SiriKali to start minimized.
2. Add your volume to SiriKali favorite's list.
3. Add the volume's password to lxqt_wallet using libsecret backend if you are using GNOME or kwallet if you are using KDE. I don't know about kwallet but i know libsecret automatically get unlocked a user logged in and SiriKali will always find it unlocked when accessing it after login and you wont see annoying prompt to enter a password to unlock a wallet.
4. Set SiriKali to automatically unlock volumes at startup.
5. Set SiriKali to automatically retrieve volume password from your preferred password storage backend.

lxqt_wallet can be accessed through SiriKali by going to "menu->settings->manage keys in wallets".

"SiriKali --help" should produce the following output. Version 1.4.1 does not produce it due to a bug i just noticed and fixed and i don't know in what version the bug was introduced.

The CLI currently does not support unlocking a volume from a favorite entry but adding the support should not be hard.

```
Version  : 1.4.1 (Compiled with Qt 5.12.4)
Copyright: 2016-2019 Francis Banyikwa,mhogomchungu@gmail.com
License  : GPLv2+

options:
        -d   Path to where a volume to be auto unlocked/mounted is located.
        -m   Tool to use to open a default file manager(default tool is xdg-open).
        -e   Start the application without showing the GUI.
        -b   A name of a backend to retrieve a password from when a volume is open from CLI.
             Supported backends are: "internal","stdin","keyfile","osxkeychain","kwallet" and "libsecret".
             The first three are always present but the rest are compile time dependencies.
             "internal" option causes SiriKali to read password from lxqt-wallet internal backend.
             "stdin" option causes SiriKali to read the password from standard input.
             "keyfile" option causes SiriKali to read the password from a file.
             "libsecret" option causes SiriKali to read password from lxqt-wallet libsecret backend.
             "kwallet" option causes SiriKali to read password from lxqt-wallet kwallet backend.
             "osxkeychain" option causes SiriKali to read password from lxqt-wallet OSX key chain backend.
        -k   When opening a volume from CLI,a value of "rw" will open the volume in read\write
             mode and a value of "ro" will open the volume in read only mode.
        -z   Full path of the mount point to be used when the volume is opened from CLI.
             This option is optional.
        -c   Set Volume Configuration File Path when a volume is opened from CLI.
        -i   Set inactivity timeout(in minutes) to dismount the volume when mounted from CLI.
        -o   Set mount options when mounting a volume from CLI.
        -f   Path to keyfile.
        -u   Unmount volume.
        -p   Print a list of unlocked volumes.
        -s   Option to trigger generation of password hash.
[ink@mtz SiriKali]$ 

```

**Comment by mhogomchungu** [comment]
Closing this one for lack of activity but feel free to post if anything comes up.
