### ISSUE TITLE
SiriKali deletes my mountpoints on unmount

### ISSUE THREAD

**Issue by rfjakob** [mhogomchungu/sirikali#13]
With SiriKali running:
```
$ ls

a  b

$ gocryptfs a b
[...]
Filesystem mounted and ready.
$ ls
a  b
$ fusermount -u b
$ ls

a
```
Where is b!?

**Comment by mhogomchungu** [comment]
congrats!!!!,you found this bug :-)

This is a hard problem to solve because SiriKali is an event based application and when an unmount event happens,it automatically removes the volume entry from the application list and then removes the mount point.

SiriKali currently has no way of knowing if it was the cause of the unmount event and its own volume was unmounted or the event was externally triggered and somebody else's volume was unmounted.

A workaround for this problem is to set "reuse mount point" option from the menu list. This option will cause SiriKali to not delete mount point on unmount events.

**Comment by rfjakob** [comment]
Maybe what you could do is to check if the mountpoint is known to sirikali
at all, and ignore the event if not?

**Comment by rfjakob** [comment]
Ps: I found this because the gocryptfs test suite  started failing in
mysterious ways when sirikali is open ;)

**Comment by mhogomchungu** [comment]
The git version should no longer delete mount points when volumes are unmounted outside of SiriKali.
