### ISSUE TITLE
Crashing on Windows 10 - Unable to connect

### ISSUE THREAD

**Issue by CurtisFeatures** [mhogomchungu/sirikali#130]
HI,

Im getting a couple of issues, Firstly I was unable to connect to an SSH source. I searched and found this issue #71 - Turns out I was missing the :/ from the end of the server address.

However when I entered my full address - SSHTEST@10.146.64.30:/ and saved it the software crashed and I was unable to reload it. If I deleted the connection from the app data folder I was able to start the software again. If I added the address is without the :/ it let me save. As soon as I entered :/ it crashed again and would not open. Sound like the same issue as #129

Let me know if you need any further information.

**Comment by CurtisFeatures** [comment]
[Sshfs sshtest@10.146.64.zip](https://github.com/mhogomchungu/sirikali/files/3858438/Sshfs.sshtest%4010.146.64.zip)

I have attached my config file from app data

Event log entries:

Faulting application name: sirikali.exe, version: 0.0.0.0, time stamp: 0x5da5bf49
Faulting module name: libstdc++-6.dll, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x40000015
Fault offset: 0x0002085d
Faulting process ID: 0x1ee8
Faulting application start time: 0x01d59e052886f31f
Faulting application path: C:\Program Files (x86)\SiriKali\sirikali.exe
Faulting module path: C:\Program Files (x86)\SiriKali\libstdc++-6.dll
Report ID: 5c3fe509-6745-4284-8d62-a654496ecacf
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket 1573840284122542157, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: sirikali.exe
P2: 0.0.0.0
P3: 5da5bf49
P4: libstdc++-6.dll
P5: 0.0.0.0
P6: 00000000
P7: 40000015
P8: 0002085d
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER74D9.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER75C4.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER75D5.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER75E2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7612.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_sirikali.exe_69982b23635b7267ef5f136cbc68435caf5ee26_6cc09d70_1f57790f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5c3fe509-6745-4284-8d62-a654496ecacf
Report Status: 268435456
Hashed bucket: 6fc04b4ef2dc666845d767665c52f04d
Cab Guid: 0

**Comment by mhogomchungu** [comment]
Your zip file has an empty file.

**Comment by CurtisFeatures** [comment]
So that looks to be the issue ( i should have noticed that).

If i create a volume with no :/ then it creates the fiel with:

{
        "autoMountVolume": "false",
        "configFilePath": "",
        "idleTimeOut": "",
        "mountOptions": "idmap=user,StrictHostKeyChecking=no",
        "mountPointPath": "Z:",
        "mountReadOnly": "",
        "postMountCommand": "",
        "postUnmountCommand": "",
        "preMountCommand": "",
        "preUnmountCommand": "",
        "reverseMode": false,
        "volumeNeedNoPassword": false,
        "volumePath": "Sshfs sshtest@10.146.64.30"
}

If i edit the file and add the :/ it still lets me use the app and connect to it (y)

However if i use the app to edit the file then it crashes and creates the empty file.

**Comment by mhogomchungu** [comment]
The git version of SiriKali no longer crashes and it generates a GUI window with below text.

As i suspected, the json library SiriKali is using does not like the input for some reason and it raises the exception below. 

The SiriKali version your using crashes because exceptions raised by the library were never caught.

```
***************************
[json.exception.parse_error.101] parse error at 1: syntax error - unexpected end of input; expected '[', '{', or a literal
Failed to parse file for reading: C:/Users/Ink/AppData/Local/sirikali/SiriKali//favorites/Sshfs ink@192.168.43.100
***************************
```

**Comment by mhogomchungu** [comment]
I think the fundamental problem is with Windows or with Qt's QFile API on windows because things work on Linux but not on Windows..

When you create a favorite's entry with an address of ```Sshfs abc@xyz:/def```, SiriKali creates a favorites entry that is in a format of ```def-blablabla.json```. SiriKali uses the last component of the address when separated with "/" when creating the favorite's entry.

When you create a favorite's entry with an address of ```Sshfs abc@xyz:/```, the last components becomes ```Sshfs abc@xyz:``` and the favorites entry created takes a form of ```Sshfs abc@xyz:-blablabla.json``` and for some reason, windows fail to create the file properly and creates it as ```Sshfs abc@xyz``` with nothing in it. In other words, windows or QFile on Windows truncates the file name at the ":" character and does not add anything in it

SiriKali creates the favorite's entry first and then loads it second and the json parser crashes when it encounters and empty file bringing SiriKali down with it.

I have uploaded a git version for windows and you can get it by clicking below link. Will appreciate if you can confirm the problem is gone with this version.

https://github.com/mhogomchungu/sirikali/releases/download/1.4.1/SiriKali-1.4.1.git.setup.exe

**Comment by CurtisFeatures** [comment]
Hi,

I can confirm that this fixed the issue and it now lets me create new as well as edit addresses to include :/

Thanks for your help on this (y)

Regards
Jamie

**Comment by CurtisFeatures** [comment]
Now when I try to connect it says I need to update to SSHFS 3.4.0 - Il do that now

**Comment by CurtisFeatures** [comment]
all working after updating to SSHFS 3.5.0

**Comment by mhogomchungu** [comment]
New version is out and it has a fix for this crash

https://github.com/mhogomchungu/sirikali/releases/tag/1.4.2
