### ISSUE TITLE
CryFS: placing cryfs.config file in diferent location with a different name will not work

### ISSUE THREAD

**Issue by codesnippy** [mhogomchungu/sirikali#135]
If I create a new volume for CryFS and choose a different location and name for the cryfs.config file SiriKali will create and mount the CryFS Volume.

If you then unmount the volume and then try to mount it again. and point to where the cryfs.config file is (only with different name. eg.: test.config) it will not mount it again.

If I try and mount the volume by hand via terminal with "cryfs -c path/to/config/test.config base/location/ mount/location/" It works fine.

Why won't sirikali mount the volume if the cryfs.config file has a different name and location ?

**Comment by mhogomchungu** [comment]
Because SiriKali supports multiple backends and it uses the config file name/extension to figure out what backend it should use.

For CryFS, the config file must be named ```cryfs.config``` or ```.cryfs.config``` for SiriKali to pick it up automatically.

If you use a different name then prefix the path to the config file you give SiriKali with ```[[[cryfs]]]```.

**Comment by mhogomchungu** [comment]
I have added the answer to your question in the FAQ

https://github.com/mhogomchungu/sirikali/wiki/Frequently-Asked-Questions#110-how-to-tell-sirikali-what-backend-to-use-if-a-custom-config-file-has-a-name-sirikali-does-not-recognize
