### ISSUE TITLE
Problem mounting gvfs directory and 3 comments

### ISSUE THREAD

**Issue by pboguslawski** [mhogomchungu/sirikali#137]
Hello,

(1)

When mounting encfs directory placed on samba share (myserver.domain.loc/myshare/MyDocs mapped with gvfs in gnome/debian 10) sirikali (1.3.6+dfsg1-1 from debian 10) throws mounting error:

```
Exit Code: 1
Exit Status: 0
-------
StdOut: 
-------
StdError: fuse: unknown option `share=myshare/MyDocs'
fuse failed.  Common problems:
 - fuse kernel module not installed (modprobe fuse)
 - invalid options -- see usage message
-------
Command: "/usr/bin/encfs"   --stdinpass    "/run/user/1023/gvfs/smb-share:server=myserver.domain.loc,share=myshare/MyDocs" "/home/me/.SiriKali/MyDocs"  -o rw,fsname=encfs@"/run/user/1023/gvfs/smb-share:server=myserver.domain.loc,share=myshare/MyDocs",subtype=encfs
-------
```

Seems there is some problem quoting gvfs samba share mount point passed to encfs.

Workaround that work: make symbolic link

`/home/me/mnt/myshare -> /run/user/1023/gvfs/smb-share:server=myserver.domain.loc,share=myshare`

and use /home/me/mnt/myshare/MyDocs as encrypted folder in sirikali.

(2)

Would be nice to have option in sirikali to display decrypted directory as bookmark in gnome files manager (and remove it on unmount); Molch Encfs Manager works this way:

https://moritzmolch.com/apps/mencfsm/index.html

(3)

Consider saving only password in gnome keyring - now sirikali stores there also other things related to volumes (things other than passwords should be stored in config files probably not in keyring).

(4)
Consider changing sirikali tray icon colors to "white only" to better suit gnome menu stuff.

Regards,
Paweł

**Comment by mhogomchungu** [comment]
I do not use gnome and my distribution does not support it making it impossible for me to just install it and troubleshoot the problems you encountered.

Will look into the issues you raised but it might take a while.

**Comment by pboguslawski** [comment]
You can reproduce problem in any linux problably without gnome/samba/gvfs stuff; just create similar directory with "special" chars like

`mkdir -p ~/run/user/1023/gvfs/smb-share:server=myserver.domain.loc,share=myshare/MyDocs`

and use is as directory with encrypted files; same error is generated (tested in Debian 10).

Considering tray icon - something scalable (SVG), outlined and monochromatic would be great; i.e. "Folder" icon from material design outline:

https://material.io/resources/icons/?icon=folder&style=outline

Regards,
Paweł

**Comment by mhogomchungu** [comment]
First issue is now fixed in the git version. Fuse uses "," character as an option separator making this character an illegal character to have in the cipher path. The trick i use is to substitute this character with something else while passing the options to fuse and reverse the substitution while reading options from the system. 

SiriKali stores only cipher path and passwords in the keyring. Why dont you want cipher paths to also be stored there?

I will look into having a way to change the icon to something else and will appreciate if you could donate an icon of your liking.

**Comment by pboguslawski** [comment]
> First issue is now fixed in the git version.

Thank you!

> SiriKali stores only cipher path and passwords in the keyring.

I saw a few (5-10 as far as I remember) items created by sirikali in gnome-keyring for only one encfs dir definition. Maybe older sirikali version (1.3.6+dfsg1-1 from debian10) has this problem. I think password managers should not be used for anything else than passwords and one encrypted dir should use only one item in password manager.

>  if you could donate an icon of your liking

Material designs icons look pretty in modern interfaces in my opinion and according to page mentioned earlier are "free for everyone to use" (Apache license version 2.0.).

One more problem noticed in sirikali (1.3.6+dfsg1-1 from debian10) in gnome: sometimes sirikali (example without any defined dirs yet) starts with incomplete UI:

![obraz](https://user-images.githubusercontent.com/8192649/72042590-436b6a00-32af-11ea-82de-8f7b82ae7735.png)

Sometimes its ok (same installation afters closing and opening sirikali again):

![obraz](https://user-images.githubusercontent.com/8192649/72042677-7a418000-32af-11ea-9915-7e362748a7d8.png)

No such problems noticed in other gtk/qt apps in the same environment.

Regards,
Paweł

**Comment by mhogomchungu** [comment]
SiriKali uses lxqt_wallet to store passwords and it has no control on how lxqt_wallet uses gnome-keyring.

SiriKali creates two entries in lxqt_wallet for each volume you add.

gnome-keyring is not well designed compared to kwallet and lxqt_wallet adds other entries in the keyring for its own internal management.

1. It adds an entry to use it to check if the keyring is opened or not.
2. It adds an entry to manage a list of all of its keys.
3. It adds an entry to manage a count of keys it is managing,

The above gives 5 entries in gnome-keyring for a single entry you added in SiriKali. Each additional entry should add only two entries in gnome-keyring.

I have not responded about the bookmark thing because i am still looking into it.

**Comment by pboguslawski** [comment]
> I have not responded about the bookmark thing because i am still looking into it.

Just tested that bookmark is created automatically by Gnome if new mountpoint is created (i.e. when SiriKali mounts decrypted directory) so please ignore (2).

**Comment by pboguslawski** [comment]
> First issue is now fixed in the git version. Fuse uses "," character as an option separator making this character an illegal character to have in the cipher path. The trick i use is to substitute this character with something else while passing the options to fuse and reverse the substitution while reading options from the system.

Just compiled sirikali from commit 53bcfdbebf3635e60e6490999e78d42d0ef97a29 in Debian 10 amd64 and now using gvfs paths works ok. Thank you!

**Comment by mhogomchungu** [comment]
Closing this one since the main issue is solved.

I don't know how to create/modify icons and i took the one currently in use from google image search.

I don't think there is anything i can do with the incomplete UI because i am not doing anything clever with the UI.

**Comment by pboguslawski** [comment]
> Just compiled sirikali from commit 7b138f7 in Debian 10 amd64 and now using gvfs paths works ok.

Mounting, reading files, creating directories, moving files (0 size - see below) in directories decrypted with encfs or gocryptfs, located on gvfs/smb shares works ok but writing files throws "write error: Operation not supported" (same problem with encfs and gocryptfs) and file size in dest dir is 0.

There was no such problems in Debian 8 using encfs over gvfs/smb (mounted with gnome encfs manager). Seems encfs/goryptfs use some operations that gvfs/smb in Debian 10 does not handle  (od encfs in Debian 10 does something more than encfs in Debian 8) - didn't found the reason.

I tried to use cryfs on gvfs/smb volume to see if it will work better with gvfs/smb but mounting it with sirikali gives similar problem with special chars in path; Cltr-D in sirikali speaks:

```
StdOut: CryFS Version 0.9.10

Password: 
Loading config file (this can take some time)...done

Mounting filesystem. To unmount, call:
$ fusermount -u "/home/me/mnt/test"
-------
StdError: fuse: unknown option `share=myshare/subdir/test'
-------
Command: "/usr/bin/cryfs"  "/run/user/1234/gvfs/smb-share:server=server.test,share=myshare/subdir/test" "/home/me/mnt/test" --  -o rw,fsname=cryfs@"/run/user/1234/gvfs/smb-share:server=server.testSiriKaliSpecialCharacter001share=myshare/subdir/test",subtype=cryfs
```

Seems there is another hack needed for cryfs over gvfs...

Regards,
Paweł

**Comment by pboguslawski** [comment]
Just tried mounting gocrypts over gvfs/sftp and its not working (similar problem with writing files, even without sirkali involved in mounting). Tried to mount cryfs over gvfs/sftp and writing files work ok.

So:
* gocryptfs has problems with writing files over gvfs (smb, sftp),
* it would be nice to be able to mount cryfs over gvfs/smb with sirikali (hack probably required as above).

Regards,
Paweł

**Comment by mhogomchungu** [comment]
I do not think its possible for SiriKali to work around this problem with cryfs and the problem should be reported to cryfs. It was possible earlier because the "," character was in a string that was passed to fuse for display purpose and SiriKali could substitute it with any other character without the backend(encfs example) or fuse caring about it and the user does not notice because SiriKali substitute it back to  "," before displaying it.

This time around, the character is in the folder path, substitute it and the backend will simply fail to locate the folder.

I have opened the bug report about this with cryfs here: https://github.com/cryfs/cryfs/issues/326
