### ISSUE TITLE
Windows: permission denied on mounted directory

### ISSUE THREAD

**Issue by neilmunday** [mhogomchungu/sirikali#140]
Hi,

I am using Windows 10 64-bit with sshfs-win to try and mount a remote directory from a Linux server using SiriKali and password less SSH.

I can mount the directory fine without SiriKali using the "map network drive" method for sshfs-win and a password.

If I use SiriKali it says that it has mounted the directory and I can see from /var/log/secure on the server that my SSH key has been accepted.

However, if I try to open the folder in Windows (e.g. Z:) where the remote directory has been mounted, Windows tells me that I do have the correct permissions to access the directory.

Any idea what I am doing wrong with SiriKali? I tried "UseNetworkDrive=yes" but it made no difference.

**Comment by mhogomchungu** [comment]
Are you saying that:
1. Connecting to a remote ssh server using sshfs-win and a password works fine.
2. Connecting to a remote ssh server using SiriKali and passwordless public key does not work and you are getting permission denied error

If the above two are connect, what is the behavior when using SiriKali and a password?

Your problem seems to be related to this[1] one.

[1] https://github.com/billziss-gh/sshfs-win/issues/101

**Comment by neilmunday** [comment]
I can use sshfs-win with a password and it works fine.

If I use sirikali with either passwordless public key or with a password I get the permission denied error.

If I use sshfs-win using the "\\sshfs.i" drive mapping approach in Windows Explorer with SSH keys it mounts fine with no issues.

So it seems to me that SiriKali isn't using the same options as sshfs-win perhaps?

In addition, if I tell SiriKali to mount a directory on the remote server that has world read/execute permissions I am able to access the directory with no errors from Windows Explorer which seems to be the behaviour some people report https://github.com/billziss-gh/sshfs-win/issues/101

Hope this helps.

**Comment by mhogomchungu** [comment]
Where is ```sshfs.i``` documented? Its not mentioned in sshfs-win's front page.

I think SiriKali usage of sshfs-win is equivalent to sshfs-win's ```sshfs.r```. Use ```sshfs.r``` and see if you will get the same result you get with SiriKali.

**Comment by neilmunday** [comment]
Apologies, a typo on my part, I meant `sshfs.k`

**Comment by mhogomchungu** [comment]
> So it seems to me that SiriKali isn't using the same options as sshfs-win perhaps?

SiriKali sets ```idmap=user``` by default and sshfs-win sets it too[1] and perhaps the problem is here. Remove the option from SiriKali and see if it helps.

It will be hard for me to test this because i can not reproduce it on my system.

[1] https://github.com/billziss-gh/sshfs-win/blob/269b543a190c9ab933ed0dd29cf63c49b3ab43d5/sshfs-win.c#L203

**Comment by mhogomchungu** [comment]
According to this bug report[1], net use runs commands as system user and i think the difference in behavior is here. SiriKali run's sshfs.exe from your account and the Windows Explorer way ultimately causes sshfs.exe to run from system account.

I think this problem is beyond SiriKali and a workaround you can use is to change folder permissions on the remote system or experiment with sshfs options.

[1] https://github.com/billziss-gh/sshfs-win/issues/149

**Comment by neilmunday** [comment]
> 
> SiriKali sets `idmap=user` by default and sshfs-win sets it too[1] and perhaps the problem is here. Remove the option from SiriKali and see if it helps.

Sadly removing `idmap=user` made no difference. I'll stick to mapping the network drive via Windows Explorer for now.

**Comment by djmemo** [comment]
I don't know if that helps you with your problem.
To solve my permission problems I had to add a mask in the `umask=000` and `create_umask=000` options.
