### ISSUE TITLE
Build code in MacOS.

### ISSUE THREAD

**Issue by KevinCWKevin** [mhogomchungu/sirikali#142]
Hi,
  I am interesting in this project and try to build the code by Qt 5.14 in MacOS. But it failed with some errors. May it build success in Qt?  
Or Could you please advise me how to build it by IDE(Qt or Xcode)?

Thanks~

**Comment by mhogomchungu** [comment]
1. I do not have a MAC.
2. I have never used a MAC computer.
3. I do not know anything about Xcode.

All the support on MAC come from users like yourself.

I know its buildable on MAC because this[1] person did it a few days ago but I do not know if they used Xcode or not.

Build instructions for MAC is here[2]. A MAC user offered them and they should work.

[1] https://github.com/mhogomchungu/sirikali/issues/141

[2] https://github.com/mhogomchungu/sirikali/blob/master/OSX_BUILD_INSTRUCTIONS

**Comment by KevinCWKevin** [comment]
Yes for [2]. I also can build success by that instructions.
But when I import project to Qt Creator (version 5.14.1), many build errors occurred. Maybe I am not know how to use Qt since I am totally new for Qt.
Anyway  Thanks for your help.

**Comment by mhogomchungu** [comment]
Closing this one as "can't fix" because i lack the tools to debug the issue.
