### ISSUE TITLE
Master key not shown when creating gocryptfs volume

### ISSUE THREAD

**Issue by rpgdev** [mhogomchungu/sirikali#145]
I do not see the master key being shown at least once after creating a gocryptfs volume. It seems gocryptfs used to show it every time the encrypted folder was mounted but this changed and now it's only shown right after creating the volume for the first time. There does not seem to be a way to get this key afterwards so it seems like an issue that sirikali doesn't show it when the volume is first created.

**Comment by mhogomchungu** [comment]
Its not possible to get the master key when SiriKali runs gocryptfs because gocryptfs doesn't 
print it when it detects its not running from the terminal. 

I think the best way to get the master key is to ask gocryptfs project to add an option to print it on demand.

Gocryptfs produces below output when SiriKali runs it to create a volume.

```
Choose a password for protecting your files.
Reading Password from stdin
Not running on a terminal, suppressing master key display
The gocryptfs filesystem has been created successfully.
You can now mount it using: gocryptfs /home/ink/333 MOUNTPOINT
```

**Comment by rpgdev** [comment]
Done. Issue: https://github.com/rfjakob/gocryptfs/issues/471

**Comment by rpgdev** [comment]
gocryptfs master key can be dumped via: https://github.com/rfjakob/gocryptfs/blob/master/Documentation/MANPAGE-XRAY.md
