### ISSUE TITLE
When volume is unmounted due to being idle, mount path is not cleared up

### ISSUE THREAD

**Issue by CoolSpot** [mhogomchungu/sirikali#148]
### Issue description
When using EncFS option "Automatically Unmount After Specified Minutes of Inactivity Is Reached.", after such volume is automatically unmounted, the path it has used (e.g. ~/.SiriKali/encfs) becomes unavailable for subsequent mounts, forcing user to use new mount path (e.g. ~/.SiriKali/encfs_1).

### Steps to reproduce
1. Configure EncFS volume mounted at "/home/username/.SiriKali/encfs"
2. Set option "Automatically Unmount After Specified Minutes of Inactivity Is Reached." to "1"
3. Mount the volume
4. Add volume to favorites
5. Wait 1 minute
6. At this point the volume should have been automatically unmounted
7. Try to re-mount the volume.
    **Observed behavior:** in the mount dialog SiriKali proposes the path "/home/username/.SiriKali/encfs_1" as a mount point.
    **Expected behavior:** SiriKali must recognize that old path is not in use anymore and can be used for new mount.

**Comment by mhogomchungu** [comment]
This is a known issue and the solution is to do the following:-

1. Click "Menu".
2. Click "Settings".
3. Go to "General Settings" tab.
4. Check "Re Use Mount Point" checkbox.

The above will cause SiriKali to reuse a mount point path if  it finds it to be already occupied and to not delete it when unmounting.

The problem is the following:

1. if SiriKali does the unmounting,  then it knows it was the one that did it and can safely remove the mount point or keep it based on user option explained above.

2. With the idle option set, encfs is the one that is doing the unmounting and SiriKali will notice the unmounting but can't safely delete the mount point because it doesn't who did the un mounting and what policy do they have about the left behind mount point path and SiriKali chooses a safe bet of not deleting it.

The problem was initially discussed here: https://github.com/mhogomchungu/sirikali/issues/13

**Comment by CoolSpot** [comment]
That works, thanks!
Maybe worth adding into FAQ.
