### ISSUE TITLE
Support Utahfs

### ISSUE THREAD

**Issue by MCOfficer** [mhogomchungu/sirikali#152]
Today a post popped up on HN showcasing [Utahfs](https://github.com/cloudflare/utahfs), yet another FUSE-based encrypted filesystem.

As such, it sounds like a possible backend for Sirikali.

**Comment by mhogomchungu** [comment]
Just tried it and i has a few issues:

1. It always runs on the foreground. SiriKali on Linux and MACOS expects its backends to be daemonized. 

2. In "/proc/self/mountinfo", its file system appears as "fuse" but it should be "fuse.utah" or something else to uniquely identify the file system. Its not possible to support it if SiriKali can't uniquely identify it.

3. In "/proc/self/mountinfo", its device path appears as a last component of a mount point path. I think it will be better if the tool sets the value to something that uniquely identify the storage provider like "gcs-bucket-name" for example.

4. They don't have a release yet and it seems premature to support it at this time.

**Comment by mhogomchungu** [comment]
Closing this one as a "can't support it".

Requirements for backends currently are:
1. Backends in Linux and MACOS should be able to  run as background processes(daemonized). This allows SiriKali to start a backend and exit and then restarted later on.
2. Backends on Windows should be able to run as a foreground process. This requires SiriKali to baby sit a running backend and prevents SiriKali from exiting if a backend is still active.

Upstream has refused to add an ability to run utahfs daemonized and reading system log files trying to figure out why utahfs has failed to start is something i do not want to do.

**Comment by mhogomchungu** [comment]
Well, you can run utahfs in SiriKali but as an unsupported file system.

1. Make sure you are running git version of utahfs and put "utahfs-client" executable somewhere where SiriKali will be able to find it like in "/usr/bin" path.
2. Run git version of SiriKali.
3. Create a file named "utahfs.json" and in it, add below content.
4. Put the file in "$HOME/.config/SiriKali/backends".
5. Restart SiriKali and SiriKali should be able to use it.
6. In SiriKali, set cipher path(mount folder) to a folder that contains utahfs-client's config file(its named utahfs.yaml). 

If SiriKali can find and run "utahfs-client" but the client refused to run because one of more of its conditions where not met, then SiriKali won't be able to notice the failure and it can't report it. You will just notice that the file system was not mounted and it will be up to you to figure out why through other means. You will also get an inconvenience of manually deleting folder at the mount point path SiriKali created.

contents of "utahfs.json".
```
{
        "configFileArgument": "-cfg %{cipherFolder}/%{configFileName}",
        "configFileNames": ["utahfs.yaml"],
        "executableName": "utahfs-client",
        "fuseNames": ["fuse.utahfs"],
        "mountControlStructure": "%{mountOptions} -mount %{mountPoint}",
        "names": ["utahfs"],
        "runsInBackGround": false,
        "requiresAPassword": false,
        "setsCipherPath": false
}
```

Below image show how mounted utahfs file system looks in SiriKali.

![Screenshot_20200625_110700](https://user-images.githubusercontent.com/3496115/85681557-13384c00-b6d4-11ea-90e7-6606211d00e7.png)

**Comment by MCOfficer** [comment]
Thanks for the overwhelming amount of information... I'm just a dumb user that needs cross-platform encryption (atm securefs does the job well enough). But maybe someone else comes along that sees use in it ;)
