### ISSUE TITLE
Appdata issues

### ISSUE THREAD

**Issue by limburgher** [mhogomchungu/sirikali#156]
Hi! There seem to be some changes to the appdata file that are needed for it to work properly.

I maintain the Fedora package of sirikali, and a user reported that even though we ship an appdata file, it wasn't appearing in GNOME software center. https://bugzilla.redhat.com/show_bug.cgi?id=1852029

After the following updates it appears, but I don't see an icon and the screenshots aren't displayed:

sed -i s/io.github.mhogomchungu.SiriKali/sirikali.desktop/g src/sirikali.appdata.xml
sed -i s/io.github.mhogomchungu.sirikali.desktop/sirikali.desktop/g src/sirikali.appdata.xml
sed -i s/20160810_215609/20190912_113741/g src/sirikali.appdata.xml
sed -i s/20160810_215641/20190912_113930/g src/sirikali.appdata.xml
sed -i s/20160810_220122/20190912_114512/g src/sirikali.appdata.xml

**Comment by mhogomchungu** [comment]
Try now with the original "sirikali.appdata.xml" file.

The problem was broken links to screenshot files because i removed old images because they no longer reflect how the GUI looks. I just returned them and the links should now work as expected.

Screenshots are fetched from here: https://github.com/mhogomchungu/sirikali/tree/master/images

**Comment by mhogomchungu** [comment]
It seems the issue is solved upstream.

**Comment by mhogomchungu** [comment]
SiriKali is now on [flathub](https://flathub.org/apps/io.github.mhogomchungu.sirikali).

Just though you should know.
