### ISSUE TITLE
Strange mount issue

### ISSUE THREAD

**Issue by pehlm** [mhogomchungu/sirikali#159]
Another problem, I have three volumes that should open 'when available', in my case it's three USB sticks which mounts when I insert them. But always when autostarted at login yet three loginboxes appear trying to open these volumes, that they shouldn't do, I must click them away. But it's working as it should if I after that insert the volumes. I think before maybe 1.4.3 that was working. 

Using the very last version 1.4.4. Hope you can help.

**Comment by mhogomchungu** [comment]
Check and make sure the option pointed to in the below image is unchecked.

If the option is checked, SiriKali will attempt to unlock all volumes in the favorites list that have auto mount option set.

![ss](https://user-images.githubusercontent.com/3496115/88663201-de108680-d0e3-11ea-92c9-354c95e33502.png)

**Comment by pehlm** [comment]
That doesn't work. I've earlier (and now) had some of the volumes autostarting at startup but some only mounted when they are available, these boxes in the image should not open. That had worked in the past and the USB volumes 'only' mounted when they were available not at startup.





![screenshot](https://user-images.githubusercontent.com/1685074/88682651-313e0580-d0f3-11ea-92b6-d7e0f7b4cc67.png)

**Comment by pehlm** [comment]
It seems that there were an option before that some volumes could automount at startup but some only when they were available, like USB volumes, this was a smart function and I hope you can restore it.

**Comment by mhogomchungu** [comment]
Favorite volumes can be set at a global level to auto mount at startup or when they become available and then you can opt out a particular favorite volume from the two global defaults by setting auto mount option off/on on a favorite entry.

I do not think there was an option to separate what favorite volume should only auto mount at start up and what volume should only auto mount when it becomes available.

What you are reporting here is a bug and the git version has a fix for it. It is a mistake to attempt to auto mount a favorites volume at start up when the favorite volume is not present.

If you can, can you use a git version and check that the problem is now gone?

**Comment by pehlm** [comment]
I understand. Unfortunately I can not test it, I do not have such a system here, I only use the DEB file. I also do not want to mess too much with my system. If you had a fresh DEB I would test it though.

**Comment by mhogomchungu** [comment]
Just made a new release and it has a fix for the reported issue and you can get a debian binary package from below link. First uninstall the version you have installed from your distro's repository before installing this package.

https://build.opensuse.org/package/binary/download/home:obs_mhogomchungu/sirikali/xUbuntu_18.04/x86_64/sirikali_1.4.5.1596305580.168aaef-0_amd64.deb

**Comment by pehlm** [comment]
It seems to work now, thank you for the fix!

**Comment by mhogomchungu** [comment]
New version is out and i recommend you update to it: https://build.opensuse.org/package/binary/download/home:obs_mhogomchungu/sirikali/xUbuntu_18.04/x86_64/sirikali_1.4.6.1596453939.9974336-0_amd64.deb
