### ISSUE TITLE
UI unresponsive

### ISSUE THREAD

**Issue by fabeit** [mhogomchungu/sirikali#171]
Dear ,

I have now been using Sirikali for months and works very well, it reconnects very quickly, thanks again for helping me set it up.

The problem I have now is that the UI is not responding, all the buttons don't respond, and the only button that works is the Menu, the horizontal scroll bar doesn't work either. I was on 1.4.6 and then tried on 1.4.7 but the same problem. Is there perhaps with some Windows dll or library or .NET framework?

I am on Win 10 1909.

Thanks in advance.

**Comment by mhogomchungu** [comment]
SiriKali does not use .Net framework and it ships with Qt libraries it needs.

Do you have a favorites entry that is set to auto mount/auto connect at program startup? I can not reproduce the issue here when using windows 10 but i suspect the problem is here.

1. Close SiriKali.
2. Rename "favorites" folder located at "C:\Users\$USER\AppData\Local\SiriKali\SiriKali" where $USER is your user name.
3.  Start SiriKali and check if the problem is still there.

**Comment by fabeit** [comment]
Excellent troubleshooting, you know your software in&out! That's the problem, so what should I do since I can't modify any setting but I don't want to delete my favorites? Thanks again.

**Comment by mhogomchungu** [comment]
You have two options:-

1. Disable auto mount feature at a global level by changing a SiriKali registry value setting named "AutoMountFavoritesOnStartUp". Information on how to change SiriKali registy settings is here[1].
2. Edit individual favorites entries in that favorites folder and set "autoMountVolume" option to false.

[1] https://github.com/mhogomchungu/sirikali/issues/162

**Comment by fabeit** [comment]
Thank you, this effect resolves the problem so I can ask is the UI. But is there any way to avoid changing the registry anytime I have to access the UI? I really need the auto mount on startup so I can't leave that off. Why is it that when auto mount is turned on the UI is not accessible? Thanks again

**Comment by mhogomchungu** [comment]
When the auto mount at startup is enabled, the following happens:-

1. The UI is disabled.
2. All volumes that are configured to auto mount are auto mounted.
3. The UI is enabled.

Something is hanging at step two and i have been unable to reproduce it.

Does it work as expected when you start SiriKali with the option to auto mount disabled and then mount them all using ```favorites->mount all``` feature?
 
What volumes to do have set to auto mount?

**Comment by fabeit** [comment]
Does it work as expected when you start SiriKali with the option to auto mount disabled and then mount them all using favorites->mount all feature?

Yes everything works when I do that.

I have all volumes set to auto mount, they are all sshfs.

**Comment by fabeit** [comment]
There's another strange thing happening. I have added two additional drives, and when I use the command Mount all I get the password prompt window only on these two new drives. However if I select these new drives from the favorites drop-down menu I am not prompted a password. Mind you that I have added the keys and the wallet for these new drives as well following the procedure you showed me a few months back. So there's something going on here.

**Comment by mhogomchungu** [comment]
Did you enable the auto mount option in those new two volumes?

![Screenshot_20201029_075855](https://user-images.githubusercontent.com/3496115/97527703-064aa280-19bd-11eb-9791-315886b3441c.png)

**Comment by mhogomchungu** [comment]
This below build and see if it will make a difference

https://github.com/mhogomchungu/sirikali/releases/download/1.4.7/SiriKali-1.4.7-dev-October-29-2020.setup.exe

**Comment by fabeit** [comment]
Thanks mate, all my volumes have the auto mount volume turned on. Tried your latest build but unfortunately same problem :-(, the mount all command prompts for password for the new volumes, but not when you are mounted individually. Did you change something in how favorites are created?

**Comment by mhogomchungu** [comment]
No i did not change anything in how favorites are handled and i suspect you are getting the prompt because SiriKali fails to mount them. 

When SiriKali has focus, press CTRL+D key combo to bring up debug window and then try again to use the mount all command to see if any error will be reported for the two new volumes.

You can set the debug window to show up at start up time by clicking "Menu->Settings" to go to the settings window and then check the box pointed to in image below.


![Screenshot_20201030_132456](https://user-images.githubusercontent.com/3496115/97694365-7f2c2600-1ab3-11eb-8d7a-596bc1dfa7c9.png)

**Comment by fabeit** [comment]
No that's not the problem I think. Nothing shows up in the debug window, after the last drive mounts correctly the window requesting the password pops-up. So it first looks for the password before mounting, or at least that's what it seems since the debug window doesn't show any message. For some reason it's like it cannot see that there's a password stored in the wallet.

*************************************
Backend took 2 seconds to unlock a volume
*************************************
-------
Exit Code: 0
Exit Status: 0
-------
StdOut:
-------
StdError:
*************************************

**Comment by mhogomchungu** [comment]
Use below build and do the mount all routine and see if the problem is still there, if it is, produce the debug window and do mount all again and post the generated logs for those two failed favorites.

https://github.com/mhogomchungu/sirikali/releases/download/1.4.7/SiriKali-1.4.7-dev-October-30-2020.setup.exe

**Comment by mhogomchungu** [comment]
You were getting the prompts because SiriKali failed to read the favorite entry from the wallet and the old code "mount all" was using and that was failing is here[1] and the code the favorites drop-down menu menu is using is here[2]. What to see here is that the favorites drop-down menu ways tries one way at line 1183 which is equivalent to the way [1] is doing it and when it fails, it tries another way at line 1189.

The fix i went with was to to make "mount all" use the favorites drop-down menu code path.

Surprisingly, i could not create a favorite entry that reproduced the issue.

[1] https://github.com/mhogomchungu/sirikali/blob/ed70636001ef41461b350ac44715307d5d1debbd/src/sirikali.cpp#L703

[2] https://github.com/mhogomchungu/sirikali/blob/95f2040555492239effc56c0647fcd8cfb0a3c1f/src/sirikali.cpp#L1183-L1189

**Comment by mhogomchungu** [comment]
Try below build to see if the UI still hangs when auto mounting at startup

https://github.com/mhogomchungu/sirikali/releases/download/1.4.7/SiriKali-1.4.7-dev-October-31-2020.setup.exe

**Comment by fabeit** [comment]
That seems to work, the favorite and menu buttons are clickable, but the other 3 buttons are not, is this what you inteded?

**Comment by mhogomchungu** [comment]
Use this[1] build and see if the problem is still there.
No, the GUI is supposed to 100% usable when auto mounting is complete.

If you can understand C++ code, the current code that is included in the build is here[2] and is very sequential. First it disables GUI elements and then it shows the GUI window and then it waits for one second and then it runs the auto mounting(line 801) and then it enables the GUI.

The one second delay is there to simulate the same behavior as if you waited for the GUI to show up without auto mounting and then selecting "mount all" from the menu.

[1] https://github.com/mhogomchungu/sirikali/releases/download/1.4.7/SiriKali-1.4.7-dev-November-09-2020.setup.exe

[2] https://github.com/mhogomchungu/sirikali/blob/04c0d2bc446162566b8c7958afeb77c1b3ee1a53/src/sirikali.cpp#L782

**Comment by fabeit** [comment]
Still no dice, I mean favorites and menu are available but not the other two. For me this is fine as I don't need to create volumes frequently, but maybe other users want the other functionalities.

I am a bit familiar with C++ but not for GUI programming, but I don't understand why you need to disable the Gui elements, why can't you just trigger the mount volume command. I am sure there is another constraint but I don't see that in the code. What if you remove the disableall? A user will not have the time to fiddle with the buttons if auto mounting is on, unless they have a very long list of volumes in auto mount.

**Comment by mhogomchungu** [comment]
The point of "disableall" and "enableall" is to show the user what state the program is in and "disableall" says "i am busy so wait".

When starting it up, the "disableall" feature will not disable the "refresh" button and it should now be possible to "enableall" by clicking the button when UI goes into the state you are seeing.

Try the new release and see if the "refresh" button works as i explained it above.

https://github.com/mhogomchungu/sirikali/releases/tag/1.4.8
