### ISSUE TITLE
Multi User Systems

### ISSUE THREAD

**Issue by jdhayes** [mhogomchungu/sirikali#172]
Hello,
On multi user systems the SiriKali main window lists all gocryptfs processes, even if they are not owned by the user running the SiriKali GUI.
This is an issue for HPC clusters and other multi user servers. I believe filtering these so that the user running the SiriKali GUI only sees gocryptfs (and other backends) processes owned by themselves would be more secure and less confusing.

**Comment by mhogomchungu** [comment]
The git version should have a solution to this problem.

Getting a list of running engines and figuring out they are running under what user in Linux and MACOS sounds like a hard problem to solve and i went with a simpler solution of checking if a mount point is accessible to the current user because FUSE by default does not allow other users to access other user's mount points.

Simply checking if a mount point is in user's home directory does not work because some users including myself use mount points that are outside of home directory.

The problem will be back if a different user creates a mount point with "-o allow_other" fuse option, do you use this option?

**Comment by mhogomchungu** [comment]
For backends that sets FUSE's fsname option, SiriKali now adds username of a person that unlocked a volume.

For volumes that are unlocked outside of SiriKali by other users with "allow_other" FUSE option(this bypasses SiriKali check discussed above), they should be unlocked with a fsname option that is in a format of "$USER@ENGINENAME@CIPHERPATH" for Sirikali to ignore them(i just added this check).

example of a gocryptfs volume unlocked by root user that now works correctly with SiriKali.

```
gocryptfs $CIPHERPATH $MOUNTPOINT -o allow_other -o fsname=root@gocryptfs@$CIPHERPATH
```

Closing it as "fixed" but would appreciate if you could confirm that it works.

**Comment by jdhayes** [comment]
I can confirm what you are saying here.
While using the latest git checkout, I indeed no longer see other users gocryptfs mounts, unless they specify "allow_other".
This is sufficent for my purposes. Thanks

**Comment by mhogomchungu** [comment]
I found a better way of solving this problem. The uid of the user that unlocks a volume is automatically  stored in the volume entry in "/proc/self/mountinfo" and SiriKali now uses this value when deciding if it should show an unlocked volume or not.

The caveat with this solution is that this functionality will break if the option is not set but all supported backends have this option set by default.

The "allow_other" problem is no longer there in the git version.

**Comment by mhogomchungu** [comment]
New version is out and i recommend you update to it

https://github.com/mhogomchungu/sirikali/releases/tag/1.4.8
