### ISSUE TITLE
Failed to locate or run YubiKey's "ykchalresp" program

### ISSUE THREAD

**Issue by OdinVex** [mhogomchungu/sirikali#176]
I am met with an error dialog of “Failed to locate or run YubiKey's "ykchalresp" program.” when attempting to create a CryFS. I do have ybchalresp installed (in fact, I use KeePassXC with YubiKey).

Edit: It slipped my mind to mention:

Linux Mint x64 20
Kernel 5.9-16
YubiKey Personalization 1.20.0-2
SiriKali 1.4.2 (Distro-supplied, may attempt to build latest and try again.)

**Comment by mhogomchungu** [comment]
What is the output of the following two commands
```
which ykchalresp
```

```
ykchalresp -V
```

**Comment by mhogomchungu** [comment]
While SiriKali main window has focus, press "CTRL+D" key combo to bring up debug window and then create a volume and post all text on the debug window.

**Comment by OdinVex** [comment]
You've hard-coded it for Slot 2. I use **Slot 1**. Maybe try Slot 1 and then Slot 2 fall-back or give an option.

/usr/bin/ykchalresp is correct.
...1.20...mentioned above. :)

`
Exit Code: 1
Exit Status: 0
-------
StdOut: 
-------
StdError: Yubikey core error: timeout
-------
Command: /usr/bin/ykchalresp -2 -i -
-------

***************************
Failed to get a responce from ykchalresp
***************************
***************************
StdOUt:
***************************
***************************

***************************
***************************
StdError:
***************************
***************************
Yubikey core error: timeout

***************************`

**Comment by mhogomchungu** [comment]
It is not hard coded.

1. Close SiriKali.
2. Open SiriKali config file located at ```~/.config/SiriKali/SiriKali.conf```
3. Modify setting named ```YkchalrespArguments``` and replace ```-2``` with ```-1```
4. Start SiriKali and try again.

ykchalresp programs adds a new new line character at the end of the output and SiriKali automatically removes it because it thinks the new line character is there to make the output look pretty when the tool is run from the command line.

If you want the new line character to not be removed then  change the option named ```yubikeyRemoveNewLine``` to false.

**Comment by OdinVex** [comment]
Hard-coded as in “no direct way (gui or cli) to specify slot.” Will follow-up shortly.
