### ISSUE TITLE
Underscore in context menu misinterpreted

### ISSUE THREAD

**Issue by Oli72** [mhogomchungu/sirikali#179]
If a favorite pathname contains an underscore, the underscore is displayed below the following letter in the context menu (to denote a hotkey). This does not affect the function, so it's not severe.
SiriKali 1.4.2, Linux Mint 20.0 Cinnamon

**Comment by mhogomchungu** [comment]
It works as expected here. 

What version of Qt are you using? It could be a bug in the Qt version you are using and they fixed it in later versions. I am using version 5.15.2.

Closing the bug report as i do not think there is anything i can do here but will appreciate a response so that the version of Qt you are using can be documented.

![Screenshot_20210218_121201](https://user-images.githubusercontent.com/3496115/108334086-a59cdb00-71e2-11eb-916c-2583347c5dad.png)

**Comment by lin-oli** [comment]
The bug is back with version 1.5.0 (Qt 5.15.3) on my installation of Linux Mint 21.1 Cinnamon.
In the previous version I used (1.4.2, Qt 5.12.5, Linux Mint 20.3 Cinnamon) the originally reported bug had gone away with some update.

**Comment by Oli72** [comment]
The bug is back with version 1.5.0 (Qt 5.15.3) on my installation of Linux Mint 21.1 Cinnamon.
In the previous version I used (1.4.2, Qt 5.12.5, Linux Mint 20.3 Cinnamon) the originally reported bug had gone away with some update.
