### ISSUE TITLE
HiDPI scaling issues

### ISSUE THREAD

**Issue by rosch100** [mhogomchungu/sirikali#180]
In a HiDPI environment, all buttons show unscaled text. That means that it is not readable and makes the app unusable.
As a workaround, I suggest to change the manifest so that it does not report to windows that it is able to handle HiDPI.

![Bildschirmfoto 2021-02-11 um 18 05 30](https://user-images.githubusercontent.com/5745224/107671298-f87f0b80-6c93-11eb-9508-757efa1eb281.png)

**Comment by mhogomchungu** [comment]
Did you go to settings menu and change options pointed to in the image below?

![Screenshot_20210211_205354](https://user-images.githubusercontent.com/3496115/107677680-97fbc880-6cab-11eb-80fe-e03c14999ef0.png)

**Comment by rosch100** [comment]
No, I did not.

It's not really possible to do that, since the buttons are not readible - there is no way to figure out, which button has "settings".

BTW - HiDPI should not be configured by the program (and certainly not by the user). Maybe, it's a Qt issue?

**Comment by mhogomchungu** [comment]
Qt documentation for HiDPI configuration is here[1] and its not possible to test them because i do not have the necessary hardware and i do not know what defaults are best.

Try the following experiments and report which one worked in changing the UI size.

Experiment 1
1. Press WINDOW_KEY+R to bring up the run dialog window and then enter "cmd" and press enter to start CMD application.
2. Enter the following command and press enter: ```set QT_ENABLE_HIGHDPI_SCALING=1```
3. Enter below command to start SiriKali.
4. ```"C:\Program Files (x86)\SiriKali\sirikali.exe"```

Experiment 2
1. Press WINDOW_KEY+R to bring up the run dialog window and then enter "cmd" and press enter to start CMD application.
2. Enter the following command and press enter: ```set QT_SCALE_FACTOR=1.1```
3. Enter below command to start SiriKali.
4. ```"C:\Program Files (x86)\SiriKali\sirikali.exe"```

[1] https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt

**Comment by mhogomchungu** [comment]
Closing this one for lack of activity.

The next version will enable by default the ```QT_ENABLE_HIGHDPI_SCALING``` but user must manually set ```QT_SCALE_FACTOR``` if they want to change it and new default value will be "1.0" instead of the current value of "1.1".

**Comment by cmanley** [comment]
I've just tried both experiments and they didn't help me. The problem these days is that many monitors are 4K with users using the text scaling recommended for their display(s) by Windows. In my case 250%. The Favorites dialog is the first dialog that pops up when clicking on the "Create Volume" button, but it's impossible to read. It also has another weird quirk that the tab key does change fields but inserts a verbatim tab in the input.
![SiriKali_weird_scaling](https://user-images.githubusercontent.com/591285/113431822-9cf01500-93dc-11eb-8c70-7dd6454b51da.png)
