### ISSUE TITLE
Folder opens in Chrome

### ISSUE THREAD

**Issue by davesteele** [mhogomchungu/sirikali#181]
Using 1.4.8, the mounted folder is now being opened by Chrome instead of Nautilus (this is not useful).

Once opened, I get two more stacked "Unlocking" dialogs.

I tried changing the handler for mime type inode/directory to Nautilus (don't recall what is was). After, "xdg-open ~" launches sirikali.

Not sure to what extent this problem is due to sirikali.

**Comment by mhogomchungu** [comment]
This problem is not on SiriKali but on broken "xdg-open" tool in your system.

You can bypass it by setting your preffered file manager directly and to do so, click menu->settings->external commands->set file manager

**Comment by davesteele** [comment]
gnome-control-center reports that "Files" controls type "folder", and that "Chrome" does not. But the folder is opening in Chrome.

Again, selecting "Open Folder" against a mounted Favorite unnecessarily opens two more Unlocking dialogs, each prompting for a password, before opening Chrome. It's the extra dialogs that prompts a bug report.

After uninstalling Chrome, Firefox is used to open the folder.

The affected system is running headless, so no menu. I see no "external commands" in gnome-control-center. I tried the fixes found [here](https://unix.stackexchange.com/questions/333254/set-standard-file-browser-for-open-containing-folder) with no joy.

**Comment by davesteele** [comment]
Also, xdg-open shows the proper behavior throughout.

**Comment by mhogomchungu** [comment]
Are you saying that "xdg-open" runs as expected when running it from the
terminal but it does not when running it through SiriKali?

What happens when you set "Files" as a folder manager in SiriKali as i
explained above? Does the problem go away?.

I was thinking of not using xdg-open as the default tool and to use each
DE's file manager for most popular DE and default to xdg-open for the rest
of DE.

Since you use GNOME for example, you will get "Files" automatically as a
default tool and you can change it later if you want.

**Comment by davesteele** [comment]
The box in question is running headless ([long story](https://davesteele.github.io/raspberrypi/2020/10/20/building-a-raspberry-pi-desktop/)). I've been running sirikali via "ssh -X" since October. It has worked fine until the last upgrade.
Yes, naked xdg-open works fine.
I'm unable to find the "external commands" menu you mention (no desktop). I played with mime types per my previous post with no effect.
The problem seems more fundamental than which opener is in use. Has the user changed - are you dropping privs?
Also, what about the two extraneous dialogs?

**Comment by mhogomchungu** [comment]
Steps to change the default file manager are below:

![Screenshot_20210320_011140](https://user-images.githubusercontent.com/3496115/111847581-28b46c80-891a-11eb-96a2-925da12bba9d.png)

![Screenshot_20210320_011227](https://user-images.githubusercontent.com/3496115/111847590-2e11b700-891a-11eb-8978-07d41fbf1f66.png)

**Comment by mhogomchungu** [comment]
Going back to your question, when SiriKali has focus, press "CTRL+D" to bring up debug window and then do the "Open Folder" routine and you should see that SiriKali calls "xdg-open" with the path to the mount path only once. Those two extra calls must come from "xdg-open"

SiriKali does not change privileges and the only change it makes to the environment "xdg-open" is using is here[1]. The problem is caused either by this change or by "xdg-open" noticing it is not connected to tty.

[1] https://github.com/mhogomchungu/sirikali/blob/08f0b7a0cf74b2681f0b00f9e3c4fdef44040d29/src/utility.cpp#L1001

**Comment by davesteele** [comment]
Sorry about that - I wasn't considering that you were talking about a Sirikali setting.

Debug log below. A CryFS of the proper volume type eventually exists. Race?


*************************************
Warning, Wallet Not Set
*************************************
*************************************
1. Processing favorite entry: /home/daves/Dropbox/CryFS
2. Favorite entry does not have a password
3. Failed to read password from wallet
*************************************
*************************************
1. Creating mount point at: /home/daves/.SiriKali/CryFS
2. Mount point does not exist, creating it
3. Mount point created successfully
*************************************
Command: "/usr/bin/cryfs" "--allow-replaced-filesystem" "--config" "/home/daves/Dropbox/CryFS/cryfs.config" "/home/daves/Dropbox/CryFS" "/home/daves/.SiriKali/CryFS" "-o" "rw,fsname=Cryfs@/home/daves/Dropbox/CryFS,subtype=Cryfs"
-------
Exit Code: 0
Exit Status: 0
-------
StdOut:
CryFS Version 0.10.2

Password: 
Deriving encryption key (this can take some time)...done

Mounting filesystem. To unmount, call:
$ cryfs-unmount "/home/daves/.SiriKali/CryFS"
-------
StdError:
*************************************
Command: "/usr/bin/xdg-open" "/home/daves/.SiriKali/CryFS"
*************************************
Favorites managing temporary entry: /home/daves/.SiriKali/CryFS
*************************************
*************************************
Unknown Volume Type Detected: /home/daves/.SiriKali/CryFS
*************************************
*************************************
Warning, Wallet Not Set
*************************************
*************************************
1. Processing favorite entry: /home/daves/.SiriKali/CryFS
2. Favorite entry does not have a password
3. Failed to read password from wallet
5. Engine requires no password or favorite need no password
*************************************
*************************************
Automounting has failed: Failed To Unlock The Volume.
Not Supported Volume Encountered.
*************************************
*************************************
Favorites managing temporary entry: file:///home/daves/.SiriKali/CryFS
*************************************
*************************************
Unknown Volume Type Detected: file:///home/daves/.SiriKali/CryFS
*************************************
*************************************
Warning, Wallet Not Set
*************************************
*************************************
1. Processing favorite entry: file:///home/daves/.SiriKali/CryFS
2. Favorite entry does not have a password
3. Failed to read password from wallet
5. Engine requires no password or favorite need no password
*************************************
*************************************
Automounting has failed: Failed To Unlock The Volume.
Not Supported Volume Encountered.
*************************************

**Comment by mhogomchungu** [comment]
From your output, SiriKali calls "xdg-open" once with a path to mount point folder and "xdg-open" calls SiriKali twice with the path to the mount point.

I think the fundamental problem here is that "xdg-open" sees SiriKali as a primary handler for folders and it calls SiriKali twice to open the mount point and then gives up and falls back to trying to open the mount point with a web browser.

I just remembered somebody sent this patch[1] to prevent SiriKali from becoming a primary handler for folders and the change was reverted because of your comment here[2].

The solution on SiriKali side is for it to not be a primary handler for folders but your system will still be broken because it will then default to opening web browsers when "xdg-open" is given a path to a mount point.

[1] https://github.com/mhogomchungu/sirikali/pull/105
[2] https://github.com/mhogomchungu/sirikali/issues/121

**Comment by davesteele** [comment]
Two things
- xdg-open works in my environment.
- I explicitly set the inode/folder mime type to be handled by Nautilus, with no effect.

#121 complained of an invalid mime type. Just remove the MimeType line from desktop?

**Comment by mhogomchungu** [comment]
Yes,i will go with removing the mimetype.

1. Create a script with below content and call it "test"

```
#!/bin/bash

export LANG=C

/usr/bin/xdg-open "$1"
```

2. Make it executable.
3. Open your CryFS volume using SiriKali
4. Open the mount point with the script with a command like:
```./test /home/daves/.SiriKali/CryFS```

Did the script work as expected and the file manager opened the mount path?

**Comment by davesteele** [comment]
I've taken steps to divorce Sirikali from folder mime types, but that script is still invoking it.
I've set the handler to Nautilus for my own use.

**Comment by mhogomchungu** [comment]
I can not recognize the DE you are using in your image.

Working on this issue now and i would like to make SiriKali default to using DE specific file managers by default.

1. What DE are you using?
2. What is its default file manager and its executable file name?
3. How can i test for the DE you are using?

**Comment by mhogomchungu** [comment]
The git version now defaults to "dolphin" on KDE and "nautilus" on GNOME and "xdg-open" on other DEs. Will expand the list of default file managers as i become aware of them.

**Comment by davesteele** [comment]
GNOME
