### ISSUE TITLE
Update to cryfs 0.9.7 : Error Backend not responding

### ISSUE THREAD

**Issue by ericogit** [mhogomchungu/sirikali#19]
I've updated cryfs to version 0.9.7 (I was on 0.9.6) My volume is encrypted with key + keyfile.
Now I get the message:
Failed to complete the task. Backend not responding.
Only thing that worked was downgrading cryfs to 0.9.6

**Comment by mhogomchungu** [comment]
The GUI in git version should now be more descriptive as it now displays backend logs to the user as the screen below shows with the error you were getting.

![screenshot_20170214_095947](https://cloud.githubusercontent.com/assets/3496115/22918693/99b11136-f29c-11e6-88e6-0167b77b3283.png)

**Comment by mhogomchungu** [comment]
"Backend not responding" was a SiriKali generic error message when it failed to complete the requested task and also failed to figure out why it failed.

The git version now no longer shows the generic error message and just forwards the backend logs  to the user hopefully to help the user solves the problem SiriKali failed to solve itself.

I am closing this one as i think the reported problem is already fixed in the git version.
