### ISSUE TITLE
Feature Request: auto mount on boot

### ISSUE THREAD

**Issue by smessmer** [mhogomchungu/sirikali#2]
It would be cool, if SiriKali could be configured to auto-mount file systems on system boot.

For example, SiriKali could have a setting that, when enabled, autostarts SiriKali on system boot. Then, each file system in the favorite list could have a setting whether it should be automounted when SiriKali starts.

**Comment by mhogomchungu** [comment]
At boot time or at login time?

At boot time but before login time will mean running with root's privileges and this will be problematic because FUSE does not like one user to access a mount point created by another user.

At login time will work and it is already possible to do this.All a user has to do is set SiriKali to run at login to unlock a volume. An example command is like below:

``` sirikali -d /abc/def -b internal -z /abc/ghi ```

Running the above command with crash version 1.0.0 and the fix is already in the git repository.

The above command tells sirikali to take unlock a volume at "/abc/def" with a key retrieved from internal wallet and create a mount point at "/abc/ghi" 

The internal wallet will generate a password prompt to unlock it if it is not set to use a blank password.

The libsecret wallet will not generate a prompt since the wallet will be auto opened when you log in if on a gnome desktop environment and will generate a prompt in other desktop environments.

The kde wallet will not generate a password prompt if the wallet is set to use an empty password.

Getting a password to do these auto unlocking will always presents security risks if a user want to not be inconvenienced at all.

For convenience,i will add an ability to manage a list of volumes that will be auto unlocked on program start when it is started with a particular option.

**Comment by mhogomchungu** [comment]
The git version now has support for what you are requesting.

Most desktop environments allow users to set applications to auto start at login time and i think it will be better if users of SiriKali will use this feature to set it to auto start at login time.

Once the application is started,click "menu->automount favorites on start up" to set the option and then restart the application.From on and until the option is unset,everytime the application is started,it will read volumes from the favorites list and attempt to auto mount them using volume keys stored in the internal backend.

What other application does this? I would like to see how they are managing the keys that used to auto unlock volumes at startup.

**Comment by smessmer** [comment]
Thanks. I'll try it out.

With EncFS, I've used https://bitbucket.org/obensonne/gnome-encfs/src for automount.
I also think, gnome-encfs-manager has such a feature.
If I'm not mistaken, both just use the gnome keyring.

**Comment by mhogomchungu** [comment]
With the latest git,you can choose what password backend to use when auto unlocking volumes on startup.

Steps to do are below:

1. Start the application atleast once.
2. Open "~/.config/SiriKali/SiriKali.conf" and then change ```AutoMountPassWordBackEnd=internal``` to ```AutoMountPassWordBackEnd=libsecret```
3. Go to "menu->key storage->gnome wallet" and then add your volumes in libsecret backend.
4. Go to "menu->favorites->manage favorites" and add your volumes you want to auto mount.
5. Select "menu->automount favorites on startup".
6. Restart the application and your volumes that are in libsecret backend and favorites list will be auto mounted.

The default backend for this feature is the internal backend and there is currently no option to change it in the GUI necessitating the manual config option change at step 2.

**Comment by mhogomchungu** [comment]
A useful option with this auto mounting feature is "-e" option that starts the minimized to tray.

**Comment by mhogomchungu** [comment]
I tried "gnome-encfs-manager" and i think "SiriKali" now works more or less the same with regards to auto mounting volumes at start up.

I am closing this bug report since the feature you requested is already in but feel free to comment if anything comes up.

**Comment by mhogomchungu** [comment]
Latest git version has a UI change for the requested feature,to enable/disable it,you must now go to "menu->auto mount->automount at start up"
