### ISSUE TITLE
Incorrect link in pages

### ISSUE THREAD

**Issue by yfdyh000** [mhogomchungu/sirikali#201]
`https://github.com/mhogomchungu/encfs/latest` in https://mhogomchungu.github.io/sirikali/

Correct to https://github.com/vgough/encfs?

**Comment by mhogomchungu** [comment]
The link is fixed now. The link to windows version is [1] and to other operating systems is [2]. The windows version uses my fork because i created an installer for it.

Thanks you very much for noticing the broken link and reporting it,

[1] https://github.com/mhogomchungu/encfs
[2] https://github.com/vgough/encfs
