### ISSUE TITLE
OSX: Add ability to install the application through brew or brew cask

### ISSUE THREAD

**Issue by mhogomchungu** [mhogomchungu/sirikali#23]

**Comment by larsnystrom** [comment]
Actually I've reconsidered this feature a little. Maybe `brew` and/or `brew cask` is not the best option for Sirikali.

There are at least four options:

1. **Clone & Compile**. Downside is it's pretty arduous, even for technical people. No central or automated way to check for updates for the end-user. Upside is that it's already "implemented" :)

2. **Mac AppStore**. Downside is that it there's an annual cost to Apple. It'll also add some restrictions to the app, like sandboxing and stuff. I don't know much about that, but I've heard it's limiting. There's also some delay when releasing new versions, due to Apple's review. Upside is that it's super simple to install and update the app for the end-user. You could also possibly charge some money for Sirikali (I think people would pay just for the convenience of installing the app from AppStore as compared to Clone & Compile) but who knows if it's going to cover what Apple charges for the developer account.

3. **Homebrew**. Downside is that Homebrew is a third party application which needs to be installed separately. It's also command-line only, so non-developers might find a bit intimidating.  Upside is that it's easier to install and update an app with Homebrew than with Clone & Compile.

4. **Disk images**. Mac has this concept of `.dmg`-files, which are a sort of disk images containing your application. When you open the disk image you'll most often be presented with the possibility of dragging the app to the Applications directory (thereby "installing" it). The downside of .dmg-files is that there's no update mechanism, so you either have to implement an update mechanism in Sirikali or just hope users visit your website once in a while to see if an update is available. Upside is it's probably the easiest way to install stuff for the average Mac-user.

Here's what a .dmg-file looks like for VLC, to install it you just drag it to the Applications shortcut.
<img width="466" alt="skarmavbild 2017-04-03 kl 14 06 54" src="https://cloud.githubusercontent.com/assets/1000370/24608452/dcd16e7a-1876-11e7-931f-7389598a0df4.png">

Here's another for Fork (https://git-fork.com)
<img width="511" alt="skarmavbild 2017-04-03 kl 14 24 17" src="https://cloud.githubusercontent.com/assets/1000370/24609023/5a1e6b24-1879-11e7-85b2-5eea9db89764.png">


So there's no "one true way" to install applications on a Mac. But what made me question making it installable through Homebrew is the fact it'll require using the Terminal, which is not something the average Mac user is used to. I think if you want Sirikali to be used by more than developers, the AppStore and/or .dmg-files is the way to go.

**Comment by mhogomchungu** [comment]
The menu has an entry to enable auto checking for updates at start up time. There is also an option in the menu to manually check for updates.

Can you create .img image file for SiriKali?

Instructions for doing so are here: https://dragly.org/2012/01/13/deploy-qt-applications-for-mac-os-x/

**Comment by larsnystrom** [comment]
I was able to create a .dmg-file using `macdeployqt`, but when I try to run the application from the .dmg-file it doesn't work. The application appears in the dock, but no window opens. `cmd+q` doesn't work and I have to force quit.

This needs a little bit more investigating.

**Comment by mhogomchungu** [comment]
Closing this one for lack of activity. Reopen when you are ready to resume.

**Comment by teras** [comment]
Any progress on this issue? Although I (believe I) could compile SIriKali from sources, I'd rather prefer either the 3rd or the 4th option to be available instead.

**Comment by mhogomchungu** [comment]
@teras 
Its impossible for me to work on those options because i do not have access to MAC computers.

Support for them will have to be provided by a MAC user like yourself.
