### ISSUE TITLE
Settings window not resizable on Gnome

### ISSUE THREAD

**Issue by Digitalone1** [mhogomchungu/sirikali#231]
Whenever I try to enlarge or maximize the following window, nothing happens:

![image](https://github.com/mhogomchungu/sirikali/assets/25790525/459cdd40-51d6-478a-a6ca-6c76e206e61b)

As a result, I can't change the options because I suppose there's a save button somewhere that I can't see and can't click it.

Is this a known bug? Any workaround?

**Comment by mhogomchungu** [comment]
![Screenshot_20230525_132153](https://github.com/mhogomchungu/sirikali/assets/3496115/7ccf5647-f7c0-4680-9d64-c9c09a7ea00f)

There is not save button and options are saved when the window is closed. What option is not not saved when you close the window?

The window not being re-sizable is by design.
