### ISSUE TITLE
Display unmounted favorites in the main window

### ISSUE THREAD

**Issue by larsnystrom** [mhogomchungu/sirikali#26]
Navigating to the favorites in Menu -> Favorites and clicking them to mount is hard from a usability point of view. It's very easy to move the mouse outside the menu so that it closes. [This site](http://uxmovement.com/navigation/why-hover-menus-do-users-more-harm-than-good/) explains this phenomena pretty well:

> One of the worse things about hover menus is that they force users to move their mouse through hover tunnels. Hover tunnels are passages that users have to move their mouse through to click an item. Older users who are less tech-savvy will often have trouble doing this. Even tech-savvy users can find it annoying that they have to move their mouse in a confined path.
>
> Hover tunnels make it harder and slower for users to navigate. When a hover menu opens, users can’t move their mouse to the item they want in a straight line. If they do, their mouse will fall off the hover path and close the menu.

But regardless of the nature of and debate concerning hover menus, I think It'd be nice if it was possible to mount a favorite from the main window, since this is a very common action.

**Comment by mhogomchungu** [comment]
I do not want:
1. To constantly be looking at my favorites list.
2. To start looking around to figure out which favorite entry is locked and which one isnt since there will have to be some sort of an indicator to distinguish the two.

As a compromise,i have moved the favorites list to the main window as shown in the image below. 

![screenshot](https://cloud.githubusercontent.com/assets/3496115/24665496/3c4e1070-1966-11e7-8808-47de7ff4a819.png)

**Comment by larsnystrom** [comment]
This is a good compromise. Thank you.
