### ISSUE TITLE
Flatpak sandbox bypass

### ISSUE THREAD

**Issue by etvt** [mhogomchungu/sirikali#285]
May I ask what is the reason behind using `flatpak-spawn --host` for some of the actions that are performed in the flatpak variant?

If both the **encrypted file to be mounted** and the **target directory** are accessible to the SiriKali Flatpak, and gocryptfs/securefs/etc is installed inside the Flatpak, why is `flatpak-spawn --host` still required?

Specifically, could tools like `fusermount` also be included within the Flatpak to handle unmounting without host access? Does the need for `flatpak-spawn --host` stem from limitations in Flatpak's handling of FUSE operations or other system-level constraints?

Having the `--talk-name=org.freedesktop.Flatpak` raises a big red warning in most flatpak stores, for example in flathub webpage:
![image](https://github.com/user-attachments/assets/b98ff875-3261-49ef-ab67-c8008f135a84)
This could discourage security-conscious users from fully trusting your excellent software.

Thanks!

**Comment by mhogomchungu** [comment]
1. These tools need fusermount to mount and unmount their file systems.

2. Fusermount is suid-root and because of this, it is not allowed to run
inside flatpak as a matter of policy for security reasons.

3. Fusermount is not bundled in flatpak runtimes.

4. Bundling fusermount with the application will not help because the
bundled version by design will not run from inside flatpak.

5. The only way to use these tools from inside flatpak is to call them from
outside flatpak where they will get access to system provides fusermount.

**Comment by etvt** [comment]
Makes sense, thanks!  
I am really hoping Flatpak will add support for this in the future without needing host spawn capabilities...
