### ISSUE TITLE
SiriKali (1.7.2) Not Finding CPPCryptFS (1.4.4.5) For Gocryptfs Mount in Windows 10

### ISSUE THREAD

**Issue by Ssurgul** [mhogomchungu/sirikali#288]
Hopefully I'm just missing something obvious.

I have the latest version of CPPCryptFS (1.4.4.5) downloaded and running on my Windows 10 64bit system. However, there's nothing to 'install'. When I download it, it just gives me a .exe file to run directly. When I run SiriKali, and try and link up to a Gocryptfs directory, the program says it can't find CPPCryptFS. I put the main CPPCryptFS executable in a directory on the system path, and I tried having both programs running simultaneously, but neither resolved this. I also placed the CPPCryptFS executable on the desktop (where the SiriKali's executable search path is pointed to), and still nothing resolved.

**Comment by mhogomchungu** [comment]
This is now fixed in the git version and you can get git versions from [here](https://github.com/mhogomchungu/sirikali/releases/tag/1.5.2).

When using this git version or a newer version when it get released,
 go to "menu->settings" and then tick the option "manage Securefs and Cppcryptfs" and then restart.

On the next restart, SiriKali will download securefs and cppcryptfs and put them where it expects to find them.

From then onwards, you can update cppcryptfs from within the app by going to 
"menu->check for updates" and then right click "cppcryptfs" and then select "update" and do the same with "cppcryptfsctl".
