### ISSUE TITLE
Feature Request: Auto mount when getting available

### ISSUE THREAD

**Issue by pehlm** [mhogomchungu/sirikali#3]
Looking forward for the new auto mount features in the coming versions. I have another auto mount feature request, gnome-encfs-manager has another feature which it should be great to have in Sirikali: if I have for example an USB stick or a portable drive with an encrypted volume on it, it auto mount the volume when I insert the external drive in the computer. In gnome-encfs-manager: "Mount when getting available". It's a whish only for Sirikali which is a great piece of software! Regards.

**Comment by mhogomchungu** [comment]
That auto mounting feature when a volume becomes available does not happen when you insert your USB stick to your computer,it happens when the file system on your USB stick is mounted on your system file system.

The distinction is crucial because doing the latter means gnome-encfs-manager is either also a general purpose mount tool and it does the mounting itself or it delegates the mounting ability to a 3rd party like udisks and i have seen no evidence of any of the above when i looked in gnome-encfs-manager source code which is in a language i do not understand(vala).

The latest git version of "SiriKali" now monitors mounting events and it can auto mount volumes that are in the favorites list when it notices the file systems where these volumes resides were mounted(ie when it notices these volumes are now available).

To enable this feature,run the latest git version atleast once, and then look at the application's config file at ```~/.config/SiriKali/SiriKali.conf" and then change ```AutoMountFavoritesOnAvailable=false``` to ```AutoMountFavoritesOnAvailable=true``` and start again "SiriKali".

To make the feature work,your system must be setup to automount file systems on devices when those devices becomes attached to your computer.

I think gnome-encfs-manager works this same way.

**Comment by mhogomchungu** [comment]
Second entry on the list in this[1] post has info on how to change the password backend from internal one to libsecret/gnome-keyring if you want to use that backend.

[1] https://github.com/mhogomchungu/sirikali/issues/2#issuecomment-241325387

**Comment by mhogomchungu** [comment]
Latest git version has now a GUI option to set/unset this feature and it can accessed through
"menu->auto mount->auto mount when available"

I am closing this feature request since the feature is already in but feel free to comment if anything comes up.

**Comment by mhogomchungu** [comment]
To be clear of how the feature is implemented,below is a step by step example of what happens when an external drive is connected and SiriKali auto mounts an encfs volume that is on the drive..

1. The external hard drive is formatted in ext4 and it has an encfs volume in it.
2. The external hard drive is connected to the computer.
3. A desktop environment notices the connected drive and auto mounts its ext4 file system..
4. SiriKali notices the mount event,looks at the mount path to see if there is a favorites volume on the mount path.
5. SiriKali auto mounts the encfs volumes on the device.

**Comment by pehlm** [comment]
Cool! A question: must I format the drive with an ext4 filesystem? Does it work vith FAT32 (MSDOS/VFAT)? Thanks a lot anyway!

**Comment by mhogomchungu** [comment]
It works with any file system your system recognizes and auto mounts at device plugin. I mentioned "ext4" as an example to make a distinction between "mounting the file system that is on the external hard drive" and "mounting the encfs volume that sits on the file system that is on the external hard drive" :-)

There are two file systems in play here and i attempted to separate them in my explanation. Dont worry about this if you still dont get it. The feature will work with any external drive that uses any file system.

**Comment by pehlm** [comment]
Well I understand it, and it was as I first thought. Just wanted to ask though. Looking forward for release!

**Comment by mhogomchungu** [comment]
The project's main page has link for binary packages for debian,fedora,ubuntu and opensuse and these packages are automatically updated periodically and the feature requested here is already in those binary packages.

Just use the binary package for your distribution if its on the list to start using the feature now.

**Comment by pehlm** [comment]
Thanks alot, I've already installed it and I have replaced gnome-encfs-manager now on my Ubuntu machine! And Sirikali is working just as expected. Thank you.

**Comment by mhogomchungu** [comment]
A newer version of SiriKali with your feature request was just released and binary packages are already available.
