### ISSUE TITLE
macOS: mount folder not always removed on unmount

### ISSUE THREAD

**Issue by eugenesvk** [mhogomchungu/sirikali#40]
Sometimes I can't get Sirikali to mount a volume, then I realize that the previous `/path/to/mount/Drive` is not deleted on previous unmount operation and Sirikali simply fails to mount (because the mount path in the favorites isn't empty).
Is there a way to fix it, so that the folder is removed (or, ideally, if the mount path is not empty it could warn you and ask to simply move the old mount path folder to trash (to avoid any data loss in case it was some user folder) and overwrite the old path)

**Comment by mhogomchungu** [comment]
Did you set your volume to auto unmount after a certain period of inactivity? 

SiriKali does not delete the mount point with this option because the backend you are using is the one that is unmounting the volume.

This is a known problem and the workaround is to set "Reuse Mount Point Option". This option will cause SiriKali to not complain when it sees a folder at the mount point during mounting and it will not delete the mount folder during unmounting.

**Comment by eugenesvk** [comment]
No, I didn't set any inactivity unmount options.
You're right, it might be an issue with the unmount command as sometimes there was indeed an issue with unmounting a folder (was likely in use by some other process) that led in the end to the folder not being removed
The **Reuse Mount Point Option** is working, thanks, will just use that option!
