### ISSUE TITLE
V1.3.0 reports as V1.2.9

### ISSUE THREAD

**Issue by davesteele** [mhogomchungu/sirikali#42]
https://github.com/mhogomchungu/sirikali/blob/master/version

**Comment by mhogomchungu** [comment]
Do you need  this version file?

I keep forgetting about it because SiriKali no longer uses it. 

"SiriKali->Menu->Check For Updates" feature used to use it but now, it gets the latest version info from parsing this[1] file. The code that fetches latest versions of SiriKali and supported backend is here[2].

[1] https://api.github.com/repos/mhogomchungu/sirikali/releases

[2] https://github.com/mhogomchungu/sirikali/blob/f4ad0c3286bd3df308a43f31a06fd858022216a4/src/checkforupdates.cpp#L201

**Comment by davesteele** [comment]
It is used by the "About" dialog, which is reporting the wrong version.

**Comment by mhogomchungu** [comment]
The "about" dialog reports only the installed version.

The installed version is set in the config file here[1]. A mistatch between the version of SiriKali and downloaded and the value set here will be another bug and unrelated to this issue.

I am going to delete the file and you should not observe any side effects.

[1] https://github.com/mhogomchungu/sirikali/blob/18ec47f2d6026958d2a974dff76d3a3a4cd6a0b8/CMakeLists.txt#L7

**Comment by mhogomchungu** [comment]
I should have asked,what "about dialog" are you referring to?

I assumed you were talking about SiriKali about dialog window and my answer above reflects this assumption. Is there another "about" dialog that you referring to?

**Comment by davesteele** [comment]
After a dpkg upgrade, I saw the old version in the about box, found the file with a grep, and reported. With a fresh install, the proper version is reported. The problem is on my end.
