### ISSUE TITLE
macOS: Mountpoint directory is named "OSXFUSE Volume 0 (encfs)"

### ISSUE THREAD

**Issue by larsnystrom** [mhogomchungu/sirikali#43]
The mounted directory is called "OSXFUSE Volume 0 (encfs)" when mounting encfs (and possibly other) volumes on macOS. I think this is related: https://github.com/osxfuse/osxfuse/issues/361

Sirikali 1.3.0

**Comment by mhogomchungu** [comment]
I think this should be done by OSXFUSE or by backends like what gocryptfs did[1].

I have added the behavior in SiriKali git version as seen here[2]. The code is there with other backends but its commented out because i dont know how they behave with in on macos.

[1] https://github.com/rfjakob/gocryptfs/commit/9f8e19b

[2] https://github.com/mhogomchungu/sirikali/commit/7097fd11e724bbd45832f4e9fea86d1d95353489

**Comment by larsnystrom** [comment]
7097fd11e724bbd45832f4e9fea86d1d95353489 solves it for encfs. I don't use any of the other drivers, so I can't test them.

**Comment by mhogomchungu** [comment]
Just made a new release of SiriKali and i recommend you update to it.
