### ISSUE TITLE
SiriKali now works on Microsoft Window

### ISSUE THREAD

**Issue by mhogomchungu** [mhogomchungu/sirikali#58]
Developed and tested it only on windows 10.

Download link and more info are here[3].

SiriKali on Micorost Windows has three limitations.

0. securefs[1] and sshfs-win[2] are the only supported backends.
1. The GUI can not be closed when a volume is unlocked.
2. A just created volume does not get auto unlocked.

The second limitation will hopefully get resolved when securefs switches to using winfsp launcher functionality on Microsoft Windows.
 
[1] https://github.com/netheril96/securefs
[2] https://github.com/billziss-gh/sshfs-win
[3] https://github.com/mhogomchungu/sirikali/releases/tag/1.3.3

**Comment by Vesnyx** [comment]
I'm currently getting a "Not Supported Volume Encountered."

Also, the file explorer setting seems to address the wrong executable. It should be "explorer.exe"

**Comment by mhogomchungu** [comment]
You have to manually tell SiriKali where the config file is if is not in the cipher folder and you can do this in two different ways:

1. On the dialog window where you enter your password, click "options" and then set the second entry with a path to the config file.

2. Add your volume to the favorites list and then set "config file path" field with a path to where the config file is located.

**Comment by Vesnyx** [comment]
I did try to do (1), but it still reported the same error.

Just tried (2), but again the same error occurs.

**Comment by mhogomchungu** [comment]
Can download again binaries and try again. SiriKali did not handle very well external configuration files on windows.

The explorer typo is fixed too with the latest binaries.

**Comment by billziss-gh** [comment]
@mhogomchungu thank you for your work on this as well as your work on SSHFS/SSHFS-Win.

@benrubson has been working on a port of EncFS to Windows, which might be of interest to you as well. See billziss-gh/winfsp#152.

I am currently focused on other work, but I am hoping to try your work soon. Adding myself here so that I get notifications.

**Comment by mhogomchungu** [comment]
@Vesnyx 

The problematic part of the code is here[1], SiriKali supports multiple backends and it has to do guess work when figuring out the type of the volume it is trying to unlock and i do not think there is another way.

[1] https://github.com/mhogomchungu/sirikali/blob/43d3cf41eaaf9973ce88a1108d67080d3922efa1/src/siritask.cpp#L834-L853

**Comment by Vesnyx** [comment]
I suppose this is because SiriKali recognizes the type of file system after the directory is selected, not before? I can see the benefit in having it automatically determine the system, but shouldn't the user be able to specify it otherwise? 

I feel like if a custom config is specified then SiriKali should manually have what type of system it is specified. Like a radio button or something. If you still want to go through a automated identification, you could check if it matches one of those names, otherwise have the user specify what type of system it is. The only issue that generates is if the filename matches with a different filesystem's config name.

**Comment by mhogomchungu** [comment]
After a directory is selected, SiriKali attempts to find out the type of the volume by looking at the extension of the config file.

The git version now has the ability to use a config file with an unknown file extension.

To use this feature, a user has to manually specify the type of the volume as a prefix to the full path to the config file.

The entry a user has to enter for a securefs volume for example that does not have ```.securefs.config``` file extension is:

```
[[[securefs]]]/full_path_to_the_config_file
```

Windows binaries with this feature will go up sometimes next week.

**Comment by mhogomchungu** [comment]
This link[1] has windows binary with the feature i explained above.

[1] https://github.com/mhogomchungu/sirikali/releases/download/1.3.3/SiriKali.sshfs.zip

**Comment by Vesnyx** [comment]
I can now successfully mount my drive. 👍
