### ISSUE TITLE
Ubuntu 18.04 build

### ISSUE THREAD

**Issue by pehlm** [mhogomchungu/sirikali#69]
I know there is a Ubuntu 18.04 1.3.3 build in universe (which i'm using) but could you add a build 1.3.4 and forward to the apt repository? Thank you!

**Comment by mhogomchungu** [comment]
I am not a SiriKali packager for ubuntu and therefore i have no say in what version of SiriKali should be included in what version of ubuntu.

I do however offer SiriKali packages for ubuntu and you can get them from here[1]. Uninstall the version you have installed from your distribution and install this one if you want 1.3.4 features. I think it will be better if you go with the "Grab binary packages directly" option. I hope the UI will be self explanatory but dont hesitate to ask if you get stuck somewhere or if you do not know how to install packages from CLI.

I am closing this one since the request is out of my control but feel free to comment if anything comes up.

[1] https://software.opensuse.org//download.html?project=home%3Aobs_mhogomchungu&package=sirikali

**Comment by pehlm** [comment]
Thank you!

**Comment by pehlm** [comment]
Same problem for Ubuntu 22.04. Maybe you forgot it or didn't have the time but could you possible add a 22.04 repository? Using your 21.10 build now. Thanks!

**Comment by mhogomchungu** [comment]
Check again, the 22.04 repository is now available.

**Comment by pehlm** [comment]
Thanks!
