### ISSUE TITLE
Problems with building on windows

### ISSUE THREAD

**Issue by 4O4** [mhogomchungu/sirikali#70]
Hi, I'm trying to build current master on windows (msvc2015) using "Build all" command in Qt Creator and I get the following messages:

```
WARNING: Failure to find: 3rdParty\lxqt_wallet\frontend\task.cpp
WARNING: Failure to find: 3rdParty\lxqt_wallet\frontend\lxqt_secret_service.cpp
WARNING: Failure to find: monitor_mountinfo.cpp
WARNING: Failure to find: monitor_mountinfo.h
WARNING: Failure to find: 3rdParty\lxqt_wallet\frontend\lxqt_secret_service.h
WARNING: Failure to find: 3rdParty\lxqt_wallet\frontend\task.cpp
WARNING: Failure to find: 3rdParty\lxqt_wallet\frontend\lxqt_secret_service.cpp
WARNING: Failure to find: monitor_mountinfo.cpp
WARNING: Failure to find: monitor_mountinfo.h
WARNING: Failure to find: 3rdParty\lxqt_wallet\frontend\lxqt_secret_service.h
Error: dependent '3rdParty\lxqt_wallet\frontend\task.cpp' does not exist.
The process "C:\Qt\Tools\QtCreator\bin\jom.exe" exited with code 2.
Error while building/deploying project sirikali (kit: Desktop Qt 5.10.1 MSVC2015 32bit)

**Comment by mhogomchungu** [comment]
Why are you trying to build against current master? Does it contain anything you want and its not in the released version?

I plan to make a new release on 01/08/2018 so you have only 8 days to wait.

Its a good thing though to have other people being able to build it on windows and thank for trying this.

I build SiriKali on windows using gcc and i have no experience with Microsoft Visual Studio and will look into this when i solve this[1] issue in my other project since they are related(both deal with Microsoft Visual Studio).

SiriKali does not work with Qt > 9.5 on windows(atleast on gcc build) since it crashes on volume unmounting and I believe this is a bug in QProcess. Start a long running task using QProcess and then kill the task using "taskkill"[2] windows tool or pkill used by encfs[3] on windows and QProcess instance will crash. 

[1] https://github.com/mhogomchungu/tasks/issues/5
[2] https://github.com/mhogomchungu/sirikali/blob/a1d45a251dcfc7ef4640b776887c40d9614692ab/src/winfsp.cpp#L477
[3] https://github.com/vgough/encfs/blob/24af76d0d9503e1bd0725f6b448c8fecb603ab56/encfs/FileUtils.cpp#L1752

**Comment by 4O4** [comment]
Yes, it contains a lot of new commits and I just blindly hope that they will solve my problems with sshfs setup which is HUGE pain to setup on windows. I thought SiriKali will make things easier, but this is the wall I'm hitting when following the steps from wiki: ![alt](https://i.imgur.com/RjeUAwP.png)

**Comment by 4O4** [comment]
@mhogomchungu I've installed QT 5.9.5 with MinGW tooling on another machine to test if it builds this way, but there's still the same error.

 I'm wondering how are you even able to build Sirikali or your other project - lxqt_wallet - while there is clearly some misconfiguration present or the file `task.cpp` simply ceased to exist at some point / never existed at all? Do your local sources differ from what is available in the repository?

**Comment by mhogomchungu** [comment]
The problem you are having with sshfs is best explained here[1]. Install the 32 bit version of sshfs and the problem will go away. The next version of SiriKali will work with both 32 bit and 64 bit versions of sshfs.

Do you have cmake installed? 

SiriKali should be buildable with QtCreator "out of the box" on windows, Running it is another issue since you will first have to copy libgcrypt libraries to the build folder for SiriKali binary to see them. I am shipping these libgcrypt binary libraries[2] intentionally so that people like you will be able to easily build SiriKali. Long term plan to move away from libgcrypt on windows and use window's native functionality. Will will continue with this path if you decide to build a package for it on windows.

Steps to atleast compile SiriKali on windows should be as follows:
1. Download SiriKali sources.
2. Start QtCreator and the go to ```Menu-> File->Open File Or Project``` and then select SiriKali's ```CMakeList.txt``` file located in the root folder.

[1] https://github.com/billziss-gh/sshfs-win/issues/38
[2] https://github.com/mhogomchungu/sirikali/tree/master/libs/lib

**Comment by mhogomchungu** [comment]
The changelog for the next version has an entry for the issue you are facing with sshfs[1]

[1] https://github.com/mhogomchungu/sirikali/blob/a1d45a251dcfc7ef4640b776887c40d9614692ab/changelog#L135

**Comment by 4O4** [comment]
Okay, everything makes sense now. I don't have any real C++ experience and I wasn't familiar with this kind of multiplatform projects. Also I didn't realize you're not even a Windows user and yet you're doing pretty amazing job supporting this platform - kudos to you!

I do however like challenges so I wanted to build this project anyway just for the sake of learning something new. I wasted a lot of time on it today already and I want to do some Qt projects anyway so any experience might be useful.

I started following LINUX_BUILD_INSTRUCTIONS together with instructions from some other project (https://github.com/tudelft3d/masbcpp/wiki/Building-on-Windows-with-CMake-and-MinGW) and made it pretty far... Recent version of CMake however generates some compiler flags (`'-Wformat-truncation=0`) which are not supported by the old g++ shipped with MinGW, so I had to install MinGW-64 and point everything in the right direction manually. 

Then I've seen your response and decided to try and open the project using CMakeList.txt instead of sirikali.pro. It looked like everything worked nicely, but I haven't managed to force Qt Designer to use MinGW-64 compilers - it just ignores my configuration changes. So I went back to the command line where I feel more comfortable. Build went smoothly, `sirikali.exe` was generated. I copied it to empty directory, also copied there the libraries that you've mentioned. Then as the last step I finally ran the only command listed in WINDOWS_BUILD_INSTRUCTIONS and it's done. After several hours of fighting I finally have my own build! :smiley: 

I've hit some other problems now (https://i.imgur.com/zcluNr6.png and https://i.imgur.com/joov1Vj.png), but It's good to know that my assumptions were correct and my initial issue was indeed fixed in master already. Shortcut for creating favorite entry for sshfs is a nice new feature too. The only thing I'm missing is the ability to edit entries in 'Manage favorites' now. 

Thank you for your help! 👍

**Comment by 4O4** [comment]
Commands for future reference (powershell):

```
> $env:PATH='D:\tools\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin;' + $env:PATH
> cd sirikali
> mkdir build
> cd build
> cmake -DQT5=true -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=C:\Qt\Qt5.9.4\5.9.4\mingw53_32 . .. -G "MinGW Makefiles"
> mingw32-make
> mkdir dist
> cp ../sirikali.exe .
> C:\Qt\Qt5.9.4\5.9.4\mingw53_32\bin\windeployqt.exe --release .\sirikali.exe
```

**Comment by mhogomchungu** [comment]
I did not know that never versions of cmake automatically add  "-Wformat-truncation=0" , somebody reported warnings generated by newer versions of gcc on my qcheckgmail[1] and i added the option yesterday to SiriKali[2] to silence the warning, i am now working on my another project named "zuluCrypt" and i added the option there too and i was just informed that the option broke the build there[3]. Working with updated tools is very annoying sometimes.

[1] https://github.com/mhogomchungu/qCheckGMail/issues/37
[2] https://github.com/mhogomchungu/sirikali/commit/a1d45a251dcfc7ef4640b776887c40d9614692ab
[3] https://travis-ci.org/mhogomchungu/zuluCrypt/builds/407718746?utm_source=email&utm_medium=notification

**Comment by mhogomchungu** [comment]
```
The only thing I'm missing is the ability to edit entries in 'Manage favorites' now.
```
This is on my todo list and its the last thing i plan to do before i make a new release. I think most people who connect to ssh servers that change their IP address regularly will want the ability to modify favorite entries. Deleting the entry to add it back with the updated IP address is annoying and i have experienced the annoyance.

**Comment by 4O4** [comment]
Are you accepting PRs? Maybe I could help and learn a thing or two by implementing this :)

**Comment by mhogomchungu** [comment]
Yes, i do and can i direct you some place else?

There is this source file[1] that needs refactoring and i think the best place to start is here.

Everything is in a header file here because i was feeling lazy and tired when i was working on this part of the functionality.

First thing to do here is to spit the header file into a header file and an implementation file.

Second thing to do is to remove libcrypt dependency on the header file and move it to the implementation file.

Third thing to do is conditional compilation where libgcrypt functionality will be on linux and MACOS ports only and windows port should use windows API.

The first two parts should be easier to do and i think you should start from here if you want to help out.

[1] https://github.com/mhogomchungu/sirikali/blob/master/src/plugins.h

**Comment by mhogomchungu** [comment]
You can build on windows now and the reported problem on this thread is solved and i think the thread should be closed too.

Open another bug report to deal with the pull request.

**Comment by 4O4** [comment]
Okay, sure I'll work on this later this week. Thanks!
