### ISSUE TITLE
sshfs-win - Could not resolve hostname g: No such host is known

### ISSUE THREAD

**Issue by 4O4** [mhogomchungu/sirikali#71]
![alt](https://i.imgur.com/joov1Vj.png)

'g:' in the error message is the mount point path I set for this volume.

Solved by appending `:/` to "Encrypted folder path" so it is `sshfs user@host:/` instead of just `sshfs user@host`

Not sure if it is a bug or if it's intended behaviour and the wiki page just needs an update (https://github.com/mhogomchungu/sirikali/wiki/Frequently-Asked-Questions#90-how-do-i-add-options-to-connect-to-an-ssh-server)

**Comment by mhogomchungu** [comment]
Since you are using SiriKali master, the proper path to add ssh entries to the favorites list is through ```menu->create volumes->sshfs```

Lets see if i can reproduce the issue on windows.

You can see all commands SiriKali issues to its backend by starting it with "--debug" option and open "SiriKali.log" file created on your desktop after every operation.

**Comment by 4O4** [comment]
> Since you are using SiriKali master, the proper path to add ssh entries to the favorites list is through menu->create volumes->sshfs

I just double checked to be sure and got the same error

Thanks for the info on the debug option, it might be useful!

**Comment by mhogomchungu** [comment]
Can confirm the bug and i have updated the wiki page and SiriKali GUI
