### ISSUE TITLE
Feature Request: One instance

### ISSUE THREAD

**Issue by illusoryOne** [mhogomchungu/sirikali#75]
Any chance you could add an option to "Allow only one instance" like some other applications have? Thanks for this wonderful piece of software, by the way :)

**Comment by mhogomchungu** [comment]
SiriKali requires only once instance to run at at time and it is a bug if you can get more than one instance running.

You are seeing more than one instance in what operating system?

**Comment by illusoryOne** [comment]
Glad to know this is not the intended behavior. I'm running Windows 10 Home, version 1803.

**Comment by mhogomchungu** [comment]
Just solved this problem and the heart of the solution is here[1], socket paths on windows are very different from linux requiring windows to be treated differently when creating a socket path. QLocalServer/QLocalSocket Qt classes are used to enforce a one instance rule.

You can get the version with the fix by downloading ```
SiriKali-setup-2018-09-18-git.exe``` binary from here[0].

Closing this one since the problem is fixed but would appreciate a confirmation the git version has actually fixed the bug on your end.

[0] https://github.com/mhogomchungu/sirikali/releases/tag/1.3.5
[1] https://github.com/mhogomchungu/sirikali/blob/f160ede8a227cf9b6047a18a777faa937a41c3d0/src/utility.cpp#L164

**Comment by illusoryOne** [comment]
This fixed it. Thanks for resolving the issue so quickly!

**Comment by mhogomchungu** [comment]
Just made a new release and i recommend you update to it.

https://github.com/mhogomchungu/sirikali/releases
