### ISSUE TITLE
Asking for key, although entry in key storage exists

### ISSUE THREAD

**Issue by smessmer** [mhogomchungu/sirikali#8]
I have a file system in my favorite list and two key storages enabled, Internal and Gnome. Both key stores have an entry for this file system (I also tried it with only one). In this entry, the ciphertext-directory is stored together with the correct key to load the file system.

However, when I click "Favorites -> Mount all", it opens a dialog and asks me for the password. Shouldn't it find the keys in the key storage?

**Comment by mhogomchungu** [comment]
git version now has the behavior you expect.

You will have to re add your favorites volumes when you update since old favorite list no longer works with new functionality.

**Comment by mhogomchungu** [comment]
The default behavior of this feature is to auto mount a volume if its key is found in a wallet and this is not always ideal since a user may want to have a say if the volume should be mounted in read only or in read/write mode. An option ```AutoMountFavoritesVolume=false``` will produce the old behavior of generating a password dialog but the key field will be auto filled with the volume password if the volume has its key in the wallet.

**Comment by smessmer** [comment]
Thanks. Automounting with the internal wallet works now. Couldn't get it to work with gnome wallet, but will open a separate issue for that.
