### ISSUE TITLE
Unable to mount gocryptfs container on macos

### ISSUE THREAD

**Issue by defragekb** [mhogomchungu/sirikali#83]
Hi, I've built sirikali.app on my mac in order to use it with gocryptfs which is installed as well and have been tested via cli.
I've created a cipherdir with sirikali just fine, but was unable to mount is as i've got the following error:

Failed To Complete The Task And Below Log was Generated By The Backend.

----------------------------------------
flag provided but not defined: -volname
Invalid command line: /usr/local/bin/gocryptfs -rw -fsname=gocryptfs@/Users/username/crgo -volname=crgo -q /Users/username/crgo /Users/username/.SiriKali/crgo. Try 'gocryptfs -help'.

When I've tried to execute the command from above manually without '-volname=crgo' part, it has been mounted just fine and even appeared in sirikali as mounted.

I'm using the latest available version of gocryptfs which is 'gocryptfs v1.6; go-fuse [vendored]; 2018-08-19 go1.10.3' installed from brew repository.
-hh shows there's no option -volname

However, in the source code of gocryptfs at https://github.com/rfjakob/gocryptfs/blob/master/mount.go I've found the following code:
`// Add a volume name if running osxfuse. Otherwise the Finder will show it as`
`// something like "osxfuse Volume 0 (gocryptfs)".`
`	if runtime.GOOS == "darwin" {`
`		mOpts.Options = append(mOpts.Options, "volname="+path.Base(args.mountpoint))`
`}`

Is it issue in the brew's version of gocryptfs? Should I build it manually?

So I'm unable to use sirikali at the moment due to the issue

Thanks

PS: Also, I'm unable to change the apps language in the options (the list doesnt open when i click on 'Select language', just no reaction at all), but this is another issue

**Comment by mhogomchungu** [comment]
The bug in SiriKali is here[1], it unconditionally adds "volname=" variable in non linux systems,

I think the bug should be reported to gocryptfs because it does not take this argument and it unconditionally set the variable internally. Gocryptfs should allow its users to set this variable to their preferred value. Will open a bug report on gocryptfs bug tracker shortly.

I do not have a mac and have no way of testing SiriKali on the platform and all the testing come from users like yourself. The language feature is broken(you said so) and i have no way of testing it and correct the problem.

[1] https://github.com/mhogomchungu/sirikali/blob/d7b0a57e57410c60906a3bab8bf23c8ecd60b9bc/src/engines/commandOptions.h#L148

**Comment by mhogomchungu** [comment]
The translations should be included in the installed folder[1], whats broken is how SiriKali points to them and the function that does it is here[2]

[1] https://github.com/mhogomchungu/sirikali/blob/d7b0a57e57410c60906a3bab8bf23c8ecd60b9bc/CMakeLists.txt#L392-L397

[2] https://github.com/mhogomchungu/sirikali/blob/d7b0a57e57410c60906a3bab8bf23c8ecd60b9bc/src/settings.cpp#L405

**Comment by mhogomchungu** [comment]
Upstream has refused to fix the problem on their end so i have fixed it on SiriKali by adding this code[1]. Can you update from git version and test if the problem is still there?

Its kind of annoying to have all these backend deciding to do the exact same things but arbitrarily differently.

You should open the language issue in its own thread if you are willing to help solve the problem.

[1] https://github.com/mhogomchungu/sirikali/blob/fa3bd18172880a70ffbd1348481a80478d20da33/src/engines/gocryptfs.cpp#L88

**Comment by defragekb** [comment]
Can confirm, the issue has been fixed! Thanks!

**Comment by mhogomchungu** [comment]
go to this[1] line and change it below text and see if it will make a difference
```
if( APPLE )
	file( WRITE ${PROJECT_BINARY_DIR}/locale_path.h "\n#define TRANSLATION_PATH \"${CMAKE_INSTALL_FULL_DATADIR}/sirikali.app/Contents/Resources/\"\n")
else()
	file( WRITE ${PROJECT_BINARY_DIR}/locale_path.h "\n#define TRANSLATION_PATH \"${CMAKE_INSTALL_FULL_DATADIR}/sirikali/translations/\"\n")
endif()
```



https://github.com/mhogomchungu/sirikali/blob/fa3bd18172880a70ffbd1348481a80478d20da33/CMakeLists.txt#L70
