### ISSUE TITLE
Feature: consolidate favorites, keys, and current mounts into single list

### ISSUE THREAD

**Issue by brainchild0** [mhogomchungu/sirikali#87]
I have used SiriKali for several days now on my Linux Mint system where I am trying to manage a handful of encrypted stores with as much automation as security permits.

I find the software very stable and featureful, and that I am able to perform all the tasks I wish, but in many cases I find that common tasks require a greater number of steps than might be necessary if some interface enhancements were considered.

In particular, I have found that managing favorites and keys can be cumbersome, each buried under a separate sequence of menus and dialog boxes.  Unifying current mounts, saved mount points, and saved keys is a primary automation benefit of the application, and I wonder whether you would consider making all of that information available in a single tabbed list in the main window.  Such a list could show all mount points, current and saved, and could facilitate mounting/unmounting of saved points and toggling favoriting of mounted points, and could provide direct access to key store information.

(A related convenience could include a summary of this list in the tray icon menu, providing an efficient means to mount and unmount.)

**Comment by mhogomchungu** [comment]
1. What version of SiriKali are you using?

2. How often do you add/remove entries in the favorites list.

3. How often do you add/remove volume keys in wallets?

I do not find the second and third activity to be "common tasks" since ideally, they should be done once /rarely and they should be out of the way to make the main UI simple, clear and not "busy".

What i find to be common is to unlock volumes and if there is a way i have not considered of how to automate this part them i will gladly add it, Currently SiriKali supports all ways i have though of how to automate this process.

For example, you can configure SiriKali to automatically retrieve a volume key from a wallet and automatically unlock a volume without showing the mount dialog window.

Another example, you can configure SiriKali to do the above automatically at program start with showing the application main window.

Most of its actions are also available of CLI.

"Menu->Favorites"(Only one click away) will show all the entries on the favorites list and another click will be all that it will take to unlock a volume if you go with configuring SiriKali in a way i explained in my first example.

**Comment by brainchild0** [comment]
Thank you for carefully considering my suggestion.  

I agree that once the automatic behavior is configured, then mounting and unmounting volumes is not difficult.

I suggest, however, that creating the configuration has many more manual steps, and is more prone to user error, than it might be if the UI layout were updated.  

For example, if I create a mount, but I want to save it to my favorites, then I must reenter the data, from a dialog box launched from a menu.  I am responsible for making sure that the data I enter as a favorite is the same for the data I entered previously, otherwise I experience unwanted behavior.

Later, if I want to save the key, then I must go to yet another dialog box, buried in the settings dialog box, and I must reenter the volume location.  And if that location changes in my favorites settings, then I must again enter a new key entry.

So three operations are occurring: mounting, creating a favorite, and storing a key.  

The element in common to all of these operations is the volume location.  Other elements are common to two of the three operations.  Key entry is common to mounting volumes and storing keys.  Designating a mount point is common mounting volumes and creating favorites. 

It would be simple, fast, and intuitive for user to do all three operations in one place.  It would not clutter the screen.  In fact the main screen could have the same simplicity it has now, with a single table and a few buttons.  But if one of the buttons was a toggle for saving or deleting the entry from the favorites, then it would be much easier to add a favorite, and much easier to find a target favorite for deletion.  And if another button was for associating a stored key with the selected mount/favorite, then it would much easier to add a key.  Or you could put all the buttons in an edit dialog box to keep them off the main screen.

I suggest thinking about a web browser.  If I want to bookmark a page, then I visit the page in the browser, and I only need to press one icon to make the site a bookmark.  It would be much less convenient if I had to copy the web address to the clipboard, launch a dialog box from the menu, and enter the address into the dialog box.  Modern browsers don't even force the user to select a bookmark folder.  If the popup is dismissed without a folder being selected, then the browser places the bookmark in a default location.

Similarly, if I have a mount, it would be really nice if I could press one button to save it as a favorite.  And it would be very nice if I would just see an icon on the table in the main page showing me that the mount information is now saved.

I am not saying that normal use is labor intensive, but I am saying that initial configuration is much more tedious than necessary.

**Comment by mhogomchungu** [comment]
I am surprised you have not commented about the size of the favorites windows and how busy it looks. Redoing the favorites windows was going to be the first thing to do when it comes to redoing GUI elements.

Your suggestions are very good but implementing them will be very disruptive and i dont think i will do them anytime soon.

**Comment by mhogomchungu** [comment]
Its been a while since i have commented here but most of what was suggested here are already implemented.

Belong functionality was added a few versions ago:
1. The favorites window was reworked and is now more manageable.
2. The context menu of an unlocked volume on the main window has an option to add the entry to the favorites.
3. When unlocking a volume, selecting to retrieve a volume key from a key store will cause SiriKali to ask a user to add the key first to the selected key store if the key is not present.

Next on the list of todo is to move management of volume keys from settings window to favorites window.

**Comment by brainchild0** [comment]
@mhogomchungu I am excited to see the improvements, but I am installing from the Opensuse Debian repository and am unable to pull a version more recent than 1.3.6  to my Linux 19.2 system.

**Comment by mhogomchungu** [comment]
What do you mean by "Opensuse Debian repository"?

The favorites window has 3 tabs now and the tabs like the three images below:

![Screenshot_20200507_195247](https://user-images.githubusercontent.com/3496115/81322695-04062c00-909d-11ea-80f2-449210fe6fa2.png)

![Screenshot_20200507_195309](https://user-images.githubusercontent.com/3496115/81322711-08cae000-909d-11ea-9540-d0663f48981a.png)

![Screenshot_20200507_195321](https://user-images.githubusercontent.com/3496115/81322735-0ff1ee00-909d-11ea-80fb-8b76126d0630.png)

**Comment by brainchild0** [comment]
> What do you mean by "Opensuse Debian repository"?

I am not referring to a feature of the application, only, as a Linux Mint user, that I am currently receiving updates using the Aptitude package manager through the Debian repository. 

The version I am currently receiving is 1.3.6.

**Comment by brainchild0** [comment]
I think that the changes made so far improve the usability of the  favorites interface.

I would not wish to make particular comments without an adequate understanding of your future plans.

**Comment by mhogomchungu** [comment]
Today i have moved options as seen in the below image from settings to favorites menu and this completes migration of options from settings window to favorites window.

Future plans are:
1. I am not going to move options in the settings window and favorites window to the main window.
2. The main window will stay as is, favorites window will deal with options that deal with favorites and password management and settings window will deal with general application options.
3. Within the favorites window, it now possible to add an entry to a default wallet without retyping it because all places that show cipher path have an option to add it the default wallet.
4. Existing functionality, when unlocking a volume, selecting to retrieve the password from a wallet will cause SiriKali to ask to first include the volume to a wallet before continuing the mounting operation.
5. Existing functionality, context menu of an unlocked volume has an option to include it to the favorites list.

The current give version now makes it a lot more convenient to manage favorites volumes and volume credentials and i think this is the best i can do.

![Screenshot_20200515_123724](https://user-images.githubusercontent.com/3496115/82036025-0bcf5d00-96a9-11ea-966f-93112aaa9d33.png)

**Comment by mhogomchungu** [comment]
Closing this one as "80% fixed".

What i have done so far is the closest i can get to what you asked for.
