### ISSUE TITLE
support mount points to existing locations

### ISSUE THREAD

**Issue by brainchild0** [mhogomchungu/sirikali#88]
SiriKali appears to enforce that a mount point is not an existing path.  In fact, if a parent of the mount point location does not exist, SiriKali creates it, according to my observations.  In a typical Linux environment, a mount point will already exist.  It is commonly an empty directory, but non-empty directories are also supported, in which case the contents are masked until the mount is cleared.  

In my tests, If I mount a `gocryptfs` system from the command line, then the mount point must exist.  If I mount it using SiriKali, it must not exist.  This conflict is inconvenient, at best.

I would request that SiriKali support the typical case, at a minimum, of mounting to an existing path.  Automatically creating directories is extra sugar that some might find useful but in my view is not the only case to consider.

**Comment by mhogomchungu** [comment]
SiriKali is in an akward position because it supports multiple backends and they do the same things but differently and at times, in a contradicting way other times.

Example, encfs on windows requires the mount point path to not exist on mounting but cryfs requires them to exist.

Encfs automatically removes the mount point on unmount but cryfs does not. 

Removing the mount point in windows on unmount is better in my opinion because the left behind folder acts in very strange ways.

Back to your request, there is an option in settings that does what you want and its called something like "reuse mount point". If this option is set SiriKali will use the mount point folder on mount and will leave it behind on unmount. I dont like this behaviou personally because i mount volumes in my hime directory and i dont want to see " useless" folders.

**Comment by brainchild0** [comment]
I understand this problem.  I will follow your suggestion.

Perhaps for better flexibility, though, it should be possible to override the global setting differently for each mount, especially if compatibility depends on limitations in the backend.

I noticed that SiriKali supports a respectable number of FUSE file systems, especially the encryption ones, as well as `sshfs`. Even so, the user is limited to whatever is currently supported, and of course many other FUSE mount types exist, including SMB, WebDAV, union, and so.  If supporting the existing backends is an issue, and yet currently users are limited to the supported ones, then perhaps you would consider transitioning to an extensible model.  Since the backend itself is installed separately by a system-dependent method, the extension might possibly be limited to a single descriptor file, such as an XML file, following a schema that directs SiriKiri about all of the particular features of that backend.  Such a design would accomplish two major objectives:

1. Support for each particular backend is moved outside the code base, making testing easier, as well as collaboration with the authors of the backend.  Given the popularity of SiriKali, it might be possible that the authors would take partial or full responsibility for maintaining the extension, allowing SiriKiri to focus on the general problem, and forcing the backend developers to make decisions that permit a uniform experience in the user interface.  
1. Users can create, share, and use extensions for backends not supported by the main development thread of SiriKali.



By the way, I would argue that a mount operation should never create or delete a mount point, and any behavior to the contrary, if caused by the backend, should be reported in the appropriate issue tracker as a bug.  It is the incorrect behavior, and is making life needlessly difficult for you, me, and everyone else.  If I were using `encfs` and seeing this behavior, I would report it.  Luckily I am using `gocryptfs`, which is following the standard.

**Comment by mhogomchungu** [comment]
The current code structure already supports extensions, they are just build in and cant be extended by users. This[1] giant class hides most of the details of backends and 98% of the work necessary in implementing a new backend is changing a few things from this[2] "unknown" backend.

Extension system as you describe it is not realistic because SiriKali is not in the position to dictate what extensions can do and what they cant. SiriKali just looks at what a backend demands and tries to accommodate it. With you way, it will only be a matter of time before an extension comes along and it needs a special way of handling something and SiriKali will either have to know it specifically and handle it differently defeating the purpose of a generalized extension system or generalizing the behavior by demanding all the rest of extensions picking up the new option and this will cause an undue burden to extension maintainers.

Its not possible to do only one thing and please everybody and this is why SiriKali has an option for almost every use cause a user may have. The current behavior when it comes to handling of mount points in linux and MACOS is the default because its the behavior i like best and use, but there is an option to change the behavior because i think SiriKali users deserves to use it the way that works best for them(within some limits ofcourse)

[1] https://github.com/mhogomchungu/sirikali/blob/master/src/engines.h

[2] https://github.com/mhogomchungu/sirikali/blob/master/src/engines/unknown.cpp

**Comment by mhogomchungu** [comment]
A short list of unique things supported backends do.

1. Securefs is the only backend on windows that does not support mount point paths.

2. Gocryptfs is the only backend on MACOS that does not support "volname" command line option.

3. Only gocryptfs has two config files(gocryptfs.conf and gocryptfs-reverse.conf)

4. Only two backends supports reverse mode(encfs and gocryptfs) and these two backends supports it differently. Encfs uses the same config file for both modes and gocryptfs uses different ones and they are located at different places.

5. Backends can not daemonise only on windows.

6. Some backends like encfs automatically mounts a volume on successful creation and others like securefs do not.

7. On windows, some backend demands mount point folder to already create on mount and others requires the mount path to not exist(this one is already discussed).

8. Backends on windows do not support unlocking of volumes in read/write mode.

9. Backends on windows "hang" on successful unlocking and hence the only way to consistently find out is an error occured or not is to parse backend output and each backend produces different outputs.

10. Encfs is the only backend that produces errors on std error, all others produces them on std out.

11. Some backends report errors using return codes and others do not requiring parsing of outputs.

These are a few differences that came to mind but i am sure there are others.

It was easier to support all these differences because i am in control of 100%  of the involved API and i can freely change them to support new types and new behavious i discover.

**Comment by brainchild0** [comment]
I understand the problems you have explained.

I was naively optimistic that perhaps a descriptor file providing the names and types of some settings fields, along with a command template into which named variables are interpolated, would be adequate to reproduce and to extend the existing functionality.

The variety of behaviors expressed by the different backends points to the need that each one is associated with particular control logic, which cannot be provided in a descriptor.

At the same time, I still believe that a more dynamic and pluggable solution is possible, and that even if the amount of redesign would be considerable, it would ultimately make the application both usable in a wider variety of contexts as well as easier to maintain.  

Currently, although the _engines_ abstract base class makes support for new backends possible without redesign of the core application, adding support for any new backend, or modifying support for any existing backend, must be done by pulling and changing the code base, building and testing the revised application, merging the changes into the release track, and distributing a new software update.  Each user has access to the same list of supported backends, and any change to this list affects every user eventually, but requires considerable time and effort before it helps anyone.  It is also beyond the power of anyone particular individual who submits an enhancement to decide whether it is merged into the core application.  If it is not, it is little help to anyone.

A large  number of people are comfortable writing simple plugins in a dynamic language, but would be unwilling or unable to submit a pull request for a C++/Qt application, such that the changes are robust enough for acceptance and integration into the core application.  In many cases, however, someone would be able to create a short script for personal use, or to be shared with a small group.  Such a script might eventually be migrated to a more reliable and robust solution, suitable for widespread distribution, or may not.  In either case, the ability to write a plugin without the effort or expertise required to merge a change into the application core is enormously helpful.

I am aware that many applications are supporting plugins in a scripted language, such that they may be dynamically added or removed at the system or user level, independent of the application core.  Python is commonly used as the language.  To be sure, a creating a plugin engine would require effort, and operating it would require an interpreter, even if, as likely in the case of Windows, it is not already available from the system.

Like I say, I recognize that such an enhancement is not trivial, but might represent an idea to consider eventually.

**Comment by mhogomchungu** [comment]
Your suggestions makes perfect sense and i think they are the most logical next place and some work in this direction is already in place since each backend currently has to fill a class as seen here with gocryptfs[1] backend to partially tell SiriKali of its properties.

Steps SiriKali will have to step to do things as you describe:

First step will be to extend this class to describe 100% of backends similarities, differences and contradictions

Second step will be to have a backend configuration file that has ability to hold all the fields of the class.

Third step will be to have SiriKali read the configuration files at start up from a set of "blessed" folders and fill up instances of the class hidden behind the common interface.

Will attempt to do it your way when i am in a tinkering mood and with lots time.

Thanks for your suggestion and i am closing this one since the primary reason for opening this report is answered.

[1] https://github.com/mhogomchungu/sirikali/blob/158a7637e3aa89f42e15e8ee9c5f14c897f90175/src/engines/gocryptfs.cpp#L24

**Comment by brainchild0** [comment]
Thanks for the discussion.  It would be wonderful if you could find a way to enhance the extensible framework to support a wider variety of store types, in addition to encrypted volumes.

For example, it would be useful to unlock an encrypted store, then to create a fuse-unionfs mount to overlay the unlocked store with a regular folder.

**Comment by mhogomchungu** [comment]
It took a while but i created a this[1] issue to keep track of the request.

Its not an easy task and it may take a while longer before it is implemented.

[1] https://github.com/mhogomchungu/sirikali/issues/95

**Comment by mhogomchungu** [comment]
It took a while but i created a this[1] issue to keep track of the request.

Its not an easy task and it may take a while longer before it is implemented.

[1] https://github.com/mhogomchungu/sirikali/issues/95

**Comment by brainchild0** [comment]
Great.  I agree it will require substantial redesign to achieve, but it will widen the breadth of usefulness of the application.  

Reflecting on the earlier discussion, I feel that the most useful design would be one that makes it easy for users to share the definitions among themselves.  For example, if someone could create and share a file called `somefstype.sk`, it is more useful than asking users to copy-and-paste a new section in a file somewhere with a static name.

Perhaps this point is clear from the previous mention of plugins, but I wanted to emphasize it anyway.

**Comment by mhogomchungu** [comment]
My current thinking is:

1. Current backends will remain put and compiled in.
2. Add another backend that is capable of loading user provided backends.
3. User provided backends will be specified in json files. SiriKali will provide a template file and users will customize it to create their backends.
4. Not use if it will be wise to allow users to override build in backends but it should be possible.
5. Not sure if it will be wise to completely replace build in backends with these json based backends files but it should be possible.
6. It will be nice but requires a whole lot of effort to have a GUI tool users will use to create their backends and have this  tool create the json files.

**Comment by brainchild0** [comment]
> My current thinking is:
> 
> 1. Current backends will remain put and compiled in.
> 2. Add another backend that is capable of loading user provided backends.
> 3. User provided backends will be specified in json files. SiriKali will provide a template file and users will customize it to create their backends.
> 4. Not use if it will be wise to allow users to override build in backends but it should be possible.
> 5. Not sure if it will be wise to completely replace build in backends with these json based backends files but it should be possible.

I like these ideas.  It would be best to keep open to the _possibility_ of eventually porting the basic backends to the custom framework.  But this part should remain only hypothetical at the beginning, not included in the first step, since preserving existing stability and functionality is critical.  It can, however, inform the way you design the customized backed framework, with respect to including adequate flexibility.  Then let users prove the effectiveness of the new style of backend by writing their own.  Nothing proves usefulness in the real world as reliably as actual use in the real world.  Once the initial problems and oversights are identified, reported, and resolved, then consider whether full replacement is wise or unwise.

You can allow overriding the existing backends, but you should deliberately make it hard to do so, in the sense of minimizing the chances of doing it accidentally.  For example, simply resolving a name collision in favor of the custom backend would be unwise because a user might use the existing name unaware of the effects.  Perhaps a boolean flag in the backend specification should be required to enable the override.




> 6. It will be nice but requires a whole lot of effort to have a GUI tool users will use to create their backends and have this  tool create the json files.

May be nice, but I wouldn't invest any effort or even thought in this part yet.  Most users who are willing and able to write a custom backend will work effectively by supplying a JSON file created in a text editor.  Features that are most valuable will be a) robust implementation, b) cogent design, c) clear, complete, and accurate documentation, d) graceful error handling, and e) useful error and other output messages, to help users writing a specification isolate the problems..  A GUI tool will substantially add to implementation and maintenance costs at the expense of the essential features.  My experience with this approach, except for expensive commercial software, is that the tool is not often maintained as often or carefully as the rest of the application.  Usually the feature set of the tool is much more limited than the full feature set of the application.  As such,  the tool quickly loses its relevance and usefulness, and becomes wasted effort.  

Very clear, current, and complete documentation, often missing from software distributions, will be about one hundred times faster to create and have about one hundred times more usefulness.

> 7. SiriKali will read these user provided backends from a set of folders located in system path(somewhere in /usr) and from user's home directory(

Yes should support a sequence of search paths to accommodate user- and system-level maintenance, as well as variation among system platforms and distributions.  Ability to configure of the search path in preferences is also nice.

**Comment by mhogomchungu** [comment]
What backend would you recommend as a test case for this feature.

**Comment by mhogomchungu** [comment]
Support for custom backends is done

https://github.com/mhogomchungu/sirikali/issues/95
