### ISSUE TITLE
Doesn't automount when key is in Gnome Wallet

### ISSUE THREAD

**Issue by smessmer** [mhogomchungu/sirikali#9]
I created a volume (with an external config file, if that makes a difference), added it to my favorites and set it to auto-mount. I also enabled auto-mounting of favorites. Then I added the key to the gnome wallet. The gnome wallet is open. But still, when I start SiriKali, it didn't mount the volume but just (silently) fails.

Then, I added the key to the internal wallet. And next time I started SiriKali, it mounted the volume. Seems it has problems accessing my Gnome Wallet in auto mount.

**Comment by mhogomchungu** [comment]
It works fine here with gnomewallet.

1. Did you change the back end that is used to retrieve passwords when automounting to "libsecret"?. There is currently no GUI way to set it so you have to do it manually. Will add it at some point in the near future. The config option to have it ```AutoMountPassWordBackEnd=libsecret``` for gnome wallet to be used instead of the internal one.

2. When you added the volume to favorites list,did you check the automout volume option.

**Comment by smessmer** [comment]
Ah I forgot the backend config option. Right, I remember you mentioned that. Thanks, it works now.

**Comment by mhogomchungu** [comment]
git version now has a GUI option to set what what backend to retrieve keys from when auto mounting volumes. You can set the option through "menu->automount favorites->automount key source".
