### ISSUE TITLE
additional favorites ignored for same source location

### ISSUE THREAD

**Issue by brainchild0** [mhogomchungu/sirikali#91]
__Observed behavior:__ In my use of SiriKali 1.3.6 using Linux Mint 19.1, a favorite is not handled correctly if it shares the source location with another favorite.  Trying to mount such a favorite simply invokes the other, even if the existing mount is already seen by application.  It is ironic that I can mount to a mount point in current use without limitation, such that I have to unmount the same number of times to actually clear the mount, but I cannot mount to a new mount point even once, except by bypassing the favorite and entering the information manually.

__Expected behavior:__ Support for multiple favorites for the same source location, such that selecting a favorite always mounts to the mount point specified by that favorite, not to one specified by a different favorite that happens to share the same source.  Also, allow the same source to mount to distinct mount points simultaneously, as long as the backend supports this case.

**Comment by mhogomchungu** [comment]
Why do you want to have the same source folder mounted to different mount points? I do not think there is a backend that supports the same volume being unlocked more than once at the same time.

SiriKali allows using a mount point that is already in use in Linux and macOS because fuse allows it. SiriKali does not allow[1] it on windows because winfsp does not allow it.

[1] https://github.com/mhogomchungu/sirikali/blob/ad6eef7d0c404000a39bd0d9cf258099294fb10a/src/keydialog.cpp#L972

**Comment by brainchild0** [comment]
Gocryptfs absolutely supports this case, I have used it many times.  Many different reasons can be considered for wanting it.  One is to present different views of the same store, to different users or to different applications.  In gocryptfs file ownership is determined entirely by which user makes a mount and with which options, not by any properties in the store.  So if multiple users are using the same store, then each user should keep a different mount.

But even if the decision is made (and I hope it is not) that support for this case is omitted as a design limitation of SiriKali, then it is still, always incorrect to activate one favorite when another is selected.  

And even if simultaneous mounts are not supported, it can and should still be supported that the same store is mounted to mount points at different times.

**Comment by mhogomchungu** [comment]
Git version should have the behavior you want.

Will appreciate a confirmation before i close this bug report.

**Comment by brainchild0** [comment]
Excellent.  I will try to build and to test as early as possible.  So far I have only used packaged binaries.

**Comment by mhogomchungu** [comment]
The favorite will transform itself into what looks like below if it detects more than one appearance of a cipher folder. to make possible to see the multiple mount points.

The main window also shows two unlocked gocryptfs volumes sharing the same cipher folder(this feels very wrong to me).

This clutters the UI so its off by default and everybody can switch to this view by flipping a setting.

I am closing this one since i dont like opened issue but will appreciate a comment if it works or not when you get around into testing it.

![screenshot](https://user-images.githubusercontent.com/3496115/52200899-fc911b00-287a-11e9-9147-25b3a025ae25.png)

**Comment by brainchild0** [comment]
I have been unsuccessful in building from the development trunk.  If I pick up the feature in a release, then I can report how it works.
