### ISSUE TITLE
Dependency KDE stack

### ISSUE THREAD

**Issue by banditopazzo** [mhogomchungu/sirikali#93]
Hi, in my recent update my package manager ask me to install many of the KDE components in my Gnome environment. I would know if now Sirikali depends on the KDE stack or maybe the dependency is just for my distribution.

I'm on Arch Linux and the package comes from AUR

Thanks

**Comment by 4O4** [comment]
`sirikali` AUR package has an **optional** dependency on `kwallet`

**Comment by mhogomchungu** [comment]
Read some of the last entries here[1] to get an idea of what is happening.

In a nutshell, the old SiriKali PKGBUILD file works fine on arch but fails on some of its derivatives. The old PKGBUILD file used internal lxqt_wallet with kde support being off by default.

The new SiriKali PKGBUILD file uses external lxqt_wallet because this configuration works with arch derivatives but the external lxqt_wallet has kde support enabled by default and this default support is the one that is pulling in kde packages.

Current defaults do not work for you and have two solutions to change them.

1. Modify SiriKali PKGBUILD file and make it depend on internal lxqt_wallet with kde support being off.
2. Modify pulled in as a dependency lxqt_wallet PKGBUILD file and disable kde wallet support.


[1] https://aur.archlinux.org/packages/sirikali/

**Comment by banditopazzo** [comment]
I solved removing the lxqt_wallet from the PKGBUILD. Thanks you
